### ISSUE TITLE
Problem when trying to build package with Pyinstaller on Windows

### ISSUE THREAD

**Issue by jlozes** [julesontheroad/NSC_BUILDER#1]
Helo,

I'm trying to build the "nut_RTR.py" file (the "nspBuild.py" file work without problem) with Pyinstaller on Windows and the package build without problem but when it is executed, I've an error on the import of "urllib3". Is this package is necessary to the script or can I remove this import and calls to it functions?

If I execute the script normaly I haven't any problem, it's only when I build the package with Pyinstaller (last version and all other packages are updated also, python is 3.6).

Thanks.

**Comment by julesontheroad** [comment]
Also you can try with https://github.com/blawar/nut if you want, you can redirect the batch call to the whole NUT with the config file.

**Comment by jlozes** [comment]
I've managed to do it by placing all the Python scripts files on the same folder (no "lib" or other folder anymore) and executing the pyinstaller command on "nut_RTR.py" with Python 3.7. By replacing some variable in the "NSCB_options.cmd" file with the adapted values, the script work normaly.

I close the issue.
