### ISSUE TITLE
Folders appear one folder up from intended location

### ISSUE THREAD

**Issue by deadair3210** [julesontheroad/NSC_BUILDER#108]
Have the script in D:\Users\User\Downloads\Console Files\Switch\NSC_BUILDER, but when verifying files, an INFO folder appears in the Switch folder instead of in the correct folder

**Comment by julesontheroad** [comment]
I think i got the issue, is because the first time you outputted a info txt file was with that function.  I think i identified it and fixed the issue in the beta.
