### ISSUE TITLE
NCA error when trying to install some NSZ converted files

### ISSUE THREAD

**Issue by chicozeb** [julesontheroad/NSC_BUILDER#110]
Hi.

I was stupid enough to convert all my games to the NSZ format without testing them. I used batch processing and compression 17 and threaded. Most of the files(about 70%) give me NCA errors when installing(golbricks, lithium and awoo installer). If I ignore the NCA error using lithium, the game installs but it does not start... I will download them all again and forget about nsz, but i think it is good to report the issue. Using 9.1.0, latest kosmos 15.1(atmosphere), sig patches installed. The same with SX OS.

**Comment by julesontheroad** [comment]
1.- Do you have all the keys?
2. Did you verify the files that give you errors, including hash?
I know the compressor is working fine since i made the parallel mode for someone with a big collection and all files verified after compressed. They also installed fine with tinfoil.
Anyway a file that verifies fine can be decompressed back to it's original state.

**Comment by chicozeb** [comment]
Loaded: H:/NSZ/Something.nsz
* Seeking icon
* Retrieving Game Information
* Generating Titles File Data
* Reading Data from Nacp
* Reading Data from Npdm
* Reading Data from Cnmt
* Verifying files
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "site-packages\eel\__init__.py", line 241, in _process_message
  File "lib\Interface.py", line 528, in getverificationdata
  File "Fs\ChromeNsp.py", line 7564, in verify_sig
  File "Fs\Nca.py", line 1904, in verify
  File "Fs\Nca.py", line 2291, in restorehead_ntr
  File "lib\aes128.py", line 304, in __init__
TypeError: object of type 'NoneType' has no len()
2020-01-14T21:21:28Z <Greenlet at 0x20eac245e18: _process_message({'call': 317.406461247468, 'name': 'getverificatio, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with TypeError



This is the type of error that shows when verifying with interface.bat. Notice that nothing appears on the chrome verification tab. This is from the interface_options.cmd

The files that don´t show errors are fine.

**Comment by chicozeb** [comment]
And yes, I have all the keys.

**Comment by deadair3210** [comment]
The only time I have seen that error is when the nsp is either incomplete or corrupted

**Comment by julesontheroad** [comment]
Your issue is here:
`key = Keys.keyAreaKey(Keys.getMasterKeyIndex(masterKeyRev), self.header.keyIndex)				
	crypto = aes128.AESECB(key)`
That's a masterkey error. Verify the keys you have with the keys checker on the config. Even if you had all if drop the lockpick file directly is has the end of lines on linux format so it won't work properly on windows, it kinda does on linux though. Is adviced to paste the keys directly on the template so the values are recognized properly.

**Comment by julesontheroad** [comment]
Specifically the rerror is saying the detected masterkey is equal to ""

**Comment by chicozeb** [comment]
I will try to change it. I used prod.keys taken with lockpick_rcm and changed the name to keys.txt... Maybe it is too much information. Didn´t check the keys template...
I will try again and report if it´s working.

**Comment by chicozeb** [comment]
DECOMPRESS A NSZ\XCZ
**************************
Decompressing H:\test.nsz
- Appending decompressed 6a8dc2f920c06ceb7edebcef13609cd6.ncz
  Writing nca header
  Writing decompressed body in plaintext
    * Section 0 is plaintext
      4000 - 98304 bytes, Crypto type 1
    * Section 0 needs decompression
      1c000 - 7111540736 bytes, Crypto type 3
      Key: b'a1773a69125a81ad5f463adf5018aba0', IV: b'00000002000000000000000000000000'
    * Section 0 needs decompression
      1a7e34000 - 20004864 bytes, Crypto type 3
      Key: b'a1773a69125a81ad5f463adf5018aba0', IV: b'00000001000000000000000000000000'

    Decompressed in 04:00 at speed: 29.7 MB/s

- Appending 8cf3161adf7018d868b6b2794eb915a2.nca
- Appending 2b6b3c4429cbc730e7742650ffe39320.nca
- Appending 2d366c05465e6c77877c70712b8615b5.cnmt.nca

Yep, that seems to be the problem... Above there´s a decompression of a file that didn´t work. It misses tik and cert... To see the files that don´t work, i only need to open interface.bat and on the information tab cheak if it has titlekey. If it doesn´t it´s a bad file.

Thanks!

**Comment by julesontheroad** [comment]
Glad we found the issue.
