### ISSUE TITLE
Exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by dansabadas** [julesontheroad/NSC_BUILDER#115]
It Happens when I'm trying to convert the Witcher 3 Willd Hunt .nsp source to the .XCI destination.
The file is big, 29 GB, retrieved via https://www.1337x.to/torrent/4052055/The-Witcher-3-Wild-Hunt-Complete-Edition-Update-NSP/

**Comment by julesontheroad** [comment]
You're missing the masterkey that game uses. Anyway for witcher 3 if you include updates also test that the file is less than 32GB.
Go to configuration, use the option to check the keys and see what you're missing. If you have it in the keys.txt file but is detected badly paste the keys directly on the template and rename the template to keys.txt.

**Comment by deadair3210** [comment]
I've also had this error when the file was damaged, the only key I'm missing is 0a

**Comment by dansabadas** [comment]
lockpick.nro did not generate my Tegra keys, but all the other ones... maybe that's why?
Anyway, after I installed the .nsp, it worked fine. Of course a much more elegant solution would be to have a .xci file

**Comment by 0Liam** [comment]
Lockpick can not dump keys past `06` (6.2.0) and was abandoned.
Use Lockpick_RCM instead.
