### ISSUE TITLE
The Program screen bugs after a few days using

### ISSUE THREAD

**Issue by Dr34dbr** [julesontheroad/NSC_BUILDER#118]
Hi Guys, 

I have this screen bug issue after using the program with sucess for a few days

Previously i used in Windows 7 and after 1 week converting games in NSP and XCI the program start bugging.

Then i update my Windows to Windows 10 and the program worked fine

After a few days the same Screen Bug issue happened:

![image](https://user-images.githubusercontent.com/62079065/76465704-ee3df880-63c4-11ea-9da4-b3b807c46d71.png)

**Comment by Dr34dbr** [comment]
Hi 

I see a closed ticket informing that the problem is in KEYS.txt archive.

Where is the place where i can find the correct Keys.txt archive for use?

My version is outdated?

I have this information inside my Keys.txt:

> aes_kek_generation_source = 4d870986c45d20722fba1053da92e8a9
> aes_key_generation_source = 89615ee05c31b6805fe58f3da24f7aa8
> bis_kek_source = 34c1a0c48258f8b4fa9e5e6adafc7e4f
> bis_key_00 = 1aac545505337cff203701f071b9dcb7c3b4f6d659f0d9fcf173b36d6be3b3e6
> bis_key_01 = 1d7787c8ca721cc98932f5d414a25a812f05c079d01806ab9d0d6394a557e792
> bis_key_02 = 209012baae1c9b6ca967a53e8f19a089d9bee0592337dd8bc9a76d3606df3b4b
> bis_key_03 = 209012baae1c9b6ca967a53e8f19a089d9bee0592337dd8bc9a76d3606df3b4b
> bis_key_source_00 = f83f386e2cd2ca32a89ab9aa29bfc7487d92b03aa8bfdee1a74c3b6e35cb7106
> bis_key_source_01 = 41003049ddccc065647a7eb41eed9c5f44424edab49dfcd98777249adc9f7ca4
> bis_key_source_02 = 52c2e9eb09e3ee2932a10c1fb6a0926c4d12e14b2a474c1c09cb0359f015f4e4
> device_key = 2e218cac677bec36f82d25b35f8011ea
> device_key_4x = eea44a0d90c43b0a9bf3e326708cea27
> eticket_rsa_kek = 19c8b441d318802bad63a5beda283a84
> eticket_rsa_kek_source = dba451124ca0a9836814f5ed95e3125b
> eticket_rsa_kekek_source = 466e57b74a447f02f321cde58f2f5535
> header_kek_source = 1f12913a4acbf00d4cde3af6d523882a
> header_key = aeaab1ca08adf9bef12991f369e3c567d6881e4e4a6a47a51f6e4877062d542d
> header_key_source = 5a3ed84fdec0d82631f7e25d197bf5d01c9b7bfaf628183d71f64d73f150b9d2
> key_area_key_application_00 = ef979e289a132c23d39c4ec5a0bba969
> key_area_key_application_01 = cdedbab97b69729073dfb2440bff2c13
> key_area_key_application_02 = 75716ed3b524a01dfe21456ce26c7270
> key_area_key_application_03 = f428306544cf5707c25eaa8bc0583fd1
> key_area_key_application_04 = 798844ec099eb6a04b26c7c728a35a4d
> key_area_key_application_05 = a57c6eecc5410ada22712eb3ccbf45f1
> key_area_key_application_06 = 2a60f6c4275df1770651d5891b8e73ec
> key_area_key_application_07 = 32221bd6ed19b938bec06b9d36ed9e51
> key_area_key_application_08 = fb20aa9e3dbf67350e86479eb431a0b3
> key_area_key_application_09 = ce8d5fa79e220d5f48470e9f21be018b
> key_area_key_application_0a = 38b865725adcf568a81d2db3ceaa5bcc
> key_area_key_application_source = 7f59971e629f36a13098066f2144c30d
> key_area_key_ocean_00 = b33813e4c9c4399c75fabc673ab4947b
> key_area_key_ocean_01 = c54166efa8c9c0f6511fa8b580191677
> key_area_key_ocean_02 = 3061ce73461e0b0409d6a33da85843c8
> key_area_key_ocean_03 = 06f170025a64921c849df168e74d37f2
> key_area_key_ocean_04 = dc857fd6dc1c6213076ec7b902ec5bb6
> key_area_key_ocean_05 = 131d76b70bd8a60036d8218c15cb610f
> key_area_key_ocean_06 = 17d565492ba819b0c19bed1b4297b659
> key_area_key_ocean_07 = 37255186f7678324bf2b2d773ea2c412
> key_area_key_ocean_08 = 4115c119b7bd8522ad63c831b6c816a6
> key_area_key_ocean_09 = 792bfc652870cca7491d1685384be147
> key_area_key_ocean_0a = dfcc9e87e61c9fba54a9b1c262d41e4d
> key_area_key_ocean_source = 327d36085ad1758dab4e6fbaa555d882
> key_area_key_system_00 = 6dd02aa15b440d6231236b6677de86bc
> key_area_key_system_01 = 4ab155e7f29a292037fd147592770b12
> key_area_key_system_02 = b7a74adeaf89c2a198c327bdff322d7d
> key_area_key_system_03 = d5aab1acd23a8aec284a316df859d377
> key_area_key_system_04 = 9b44b45b37de9d14754b1d22c2ca742c
> key_area_key_system_05 = 0012e957530d3dc7af34fbbe6fd44559
> key_area_key_system_06 = 01744e3b0818445cd54ee9f89da43192
> key_area_key_system_07 = d0d30e46f5695b875f11522c375c5a80
> key_area_key_system_08 = bd06cb1b86bd5c433667470a09eb63de
> key_area_key_system_09 = e19f788f658eda8bbf34a1dd2a9503a9
> key_area_key_system_0a = 7070e7ff5cfe448630143a9874903c38
> key_area_key_system_source = 8745f1bba6be79647d048ba67b5fda4a
> keyblob_00 = f759024f8199101dddc1ef91e6eecf37e24b95ac9272f7ae441d5d8060c843a48322d21cdd06d4fc958c68d3800eb4db939ffbec930177f77d136144ff615aa8835e811bb958deda218f8486b5a10f531b30cb9d269645ac9fc25c53fc80525e56bd3602988a9fcf06bbf99ca910ad6530791d512c9d57e17abf49220de6419bf4eca1685c1e4df77f19db7b44a985ca
> keyblob_01 = bd27264ae07e979756411d0c66e679e3c50851f3e902d9c2cd1a438b948159a517ec1566c10570326ea2697ee62da46f14bb5d581bfc06fd0c9387ea33d2d4dc63e7809ba90f03dd2c7112ffbfa548951b9b8c688b5e4f2951d24a73da29c668154a5d4838dba71ee068ace83fe720e8c2a495c596f73525dc3c05994b40ad27f8c60322f75cd548b821af9162e16f76
> keyblob_02 = a3d4a8e153b8e6ae6e6aef3e8f219cb4b7790f47856accc76268f9afa99a1ff8b1a72f63d1f99f480a3c1532078bb59abdd25203cfb12a38b33e9ba6a09afb6f24283b3ba76a0161230a73669ddf5493c2b7919d094fd795b484794854f71e4f4c672245d7770e29397722444d111b4229cdbf35707b70634ea8f140766e884cc580cb1e2d9aa9866ffef920010fc409
> keyblob_03 = 1558f525ae8c5be9243fb6d8a8b0a8ee0e886a59035668740a936619b7a5c83e821198b171d18e51445054df68688e45703b936818a827d8e540dd6bef2e11ec9ddc6cfe5fc736dd769b9f6e0a23a62e2e5f49e86143646a04ec3a23f828373a336a5c224a91f8a0c6c6a7b5844dd6415804209f83c943aeca9cfd856db6bd4ec32009c8cb268ed053052c9237dfd8bc
> keyblob_04 = 9fbeb1957fc1629e08b753a9086d6e01ffb4f11466b7417e3fa7f5f1efb754406704fd75afaf91a408a0b524c1fc80d36c2046fa4757412efe4c11e382f72e8a10d90ed580017d9deb87af2549b6b02661af48ff94f6072c0fef7fc2833b8bdae503898e2e927ac0663e8b6391dd4f1d685313935e2c48ece7d177c88bc9c883ede36c3677495784b838d7265c6ba7a1
> keyblob_05 = 94a92da1d73c2b3e165c891ced5607fc6628ca2a0654f3fbc05711c063377c6e9c96a9d0192e530dd510e4fd41aa62ef4213c5f6e059e7e21db098a9b22d1e6c29bee148aaef15c52549d9165de96e85b0d029ecdc5843e2f32cb18be707eec61909cf3385d45bc2a4c8d76e9bfad5a40c4b92dcb982aa50d474897ac9ebb5351a7015dcc277a08f1214ad41384d7941
> keyblob_key_00 = 862f0708e121740d467209a4c7d57f8e
> keyblob_key_01 = 0340576ca243d2da03654b2c6bd595a4
> keyblob_key_02 = 395186fe46fd4e81a86c72765f1e968b
> keyblob_key_03 = b0bb57fde671a510775e06d7054b9567
> keyblob_key_04 = 100e550c9331c34ae678fd26f3bf93c7
> keyblob_key_05 = 34fce7942915e0d2eafc051a7ce141f8
> keyblob_key_source_00 = df206f594454efdc7074483b0ded9fd3
> keyblob_key_source_01 = 0c25615d684ceb421c2379ea822512ac
> keyblob_key_source_02 = 337685ee884aae0ac28afd7d63c0433b
> keyblob_key_source_03 = 2d1f4880edeced3e3cf248b5657df7be
> keyblob_key_source_04 = bb5a01f988aff5fc6cff079e133c3980
> keyblob_key_source_05 = d8cce1266a353fcc20f32d3b517de9c0
> keyblob_mac_key_00 = 1dac2774070b09726e1c71b7a2314acc
> keyblob_mac_key_01 = 6d2091dbb5eda4ed21dfcbbd05c76eb6
> keyblob_mac_key_02 = 4e0b6480954a20037eb89fbd3f7d0373
> keyblob_mac_key_03 = 9c4c2c3587cbf04222c229e8a594c8ad
> keyblob_mac_key_04 = 2bde32eee7a9fc7866b402b3791eaec3
> keyblob_mac_key_05 = 3ab92eca5f50ea1e5b9b8a75958e7889
> keyblob_mac_key_source = 59c7fb6fbe9bbe87656b15c0537336a5
> master_kek_00 = f759024f8199101dddc1ef91e6eecf37
> master_kek_01 = bd27264ae07e979756411d0c66e679e3
> master_kek_02 = a3d4a8e153b8e6ae6e6aef3e8f219cb4
> master_kek_03 = 1558f525ae8c5be9243fb6d8a8b0a8ee
> master_kek_04 = 9fbeb1957fc1629e08b753a9086d6e01
> master_kek_05 = 94a92da1d73c2b3e165c891ced5607fc
> master_kek_source_06 = 374b772959b4043081f6e58c6d36179a
> master_kek_source_07 = 9a3ea9abfd56461c9bf6487f5cfa095c
> master_kek_source_08 = dedce339308816f8ae97adec642d4141
> master_kek_source_09 = 1aec11822b32387a2bedba01477e3b67
> master_kek_source_0a = 303f027ed838ecd7932534b530ebca7a
> master_key_00 = c2caaff089b9aed55694876055271c7d
> master_key_01 = 54e1b8e999c2fd16cd07b66109acaaa6
> master_key_02 = 4f6b10d33072af2f250562bff06b6da3
> master_key_03 = 84e04ec20b9373818c540829cf147f3d
> master_key_04 = cfa2176790a53ff74974bff2af180921
> master_key_05 = c1dbedcebf0dd6956079e506cfa1af6e
> master_key_06 = 0aa90e6330cdc12d819b3254d11a4e1e
> master_key_07 = 929f86fbfe4ef7732892bf3462511b0e
> master_key_08 = 23cfb792c3cb50cd715da0f84880c877
> master_key_09 = 75c93b716255319b8e03e14c19dea64e
> master_key_0a = 73767484c73088f629b0eeb605f64aa6
> master_key_source = d8a2410ac6c59001c61d6a267c513f3c
> package1_key_00 = f4eca1685c1e4df77f19db7b44a985ca
> package1_key_01 = f8c60322f75cd548b821af9162e16f76
> package1_key_02 = c580cb1e2d9aa9866ffef920010fc409
> package1_key_03 = c32009c8cb268ed053052c9237dfd8bc
> package1_key_04 = ede36c3677495784b838d7265c6ba7a1
> package1_key_05 = 1a7015dcc277a08f1214ad41384d7941
> package2_key_00 = a35a19cb14404b2f4460d343d178638d
> package2_key_01 = a0dd1eacd438610c85a191f02c1db8a8
> package2_key_02 = 7e5ba2aafd57d47a85fd4a57f2076679
> package2_key_03 = bf03e9889fa18f0d7a55e8e9f684323d
> package2_key_04 = 09df6e361e28eb9c96c9fa0bfc897179
> package2_key_05 = 444b1a4f9035178b9b1fe262462acb8e
> package2_key_06 = 442cd9c21cfb8914587dc12e8e7ed608
> package2_key_07 = 70c821e7d6716feb124acbac09f7b863
> package2_key_08 = 8accebcc3d15a328a48365503f8369b6
> package2_key_09 = f562a7c6c42e3d4d3d13ffd504d77346
> package2_key_0a = 0803167ec7fc0bc753d8330e5592a289
> package2_key_source = fb8b6a9c7900c849efd24d854d30a0c7
> per_console_key_source = 4f025f0eb66d110edc327d4186c2f478
> retail_specific_aes_key_source = e2d6b87a119cb880e822888a46fba195
> rsa_oaep_kek_generation_source = a8ca938434127fda82cc1aa5e807b112
> rsa_private_kek_generation_source = ef2cb61a56729b9157c38b9316784ddd
> save_mac_kek_source = d89c236ec9124e43c82b038743f9cf1b
> save_mac_key = 9654216726600fe8cb83147a293ddcbb
> save_mac_key_source = e4cd3d4ad50f742845a487e5a063ea1f
> save_mac_sd_card_kek_source = 0489ef5d326e1a59c4b7ab8c367aab17
> save_mac_sd_card_key_source = 6f645947c56146f9ffa045d595332918
> sd_card_custom_storage_key_source = 370c345e12e4cefe21b58e64db52af354f2ca5a3fc999a47c03ee004485b2fd0
> sd_card_kek_source = 88358d9c629ba1a00147dbe0621b5432
> sd_card_nca_key_source = 5841a284935b56278b8e1fc518e99f2b67c793f0f24fded075495dca006d99c2
> sd_card_save_key_source = 2449b722726703a81965e6e3ea582fdd9a951517b16e8f7f1f68263152ea296a
> sd_seed = ea597dbc14f2163aefb6d750377aae8d
> secure_boot_key = fb36cd2450f52ccad625d154f6dd0a91
> ssl_rsa_kek = b011100660d1dccbad1b1b733afa9f95
> ssl_rsa_kek_source_x = 7f5bb0847b25aa67fac84be23d7b6903
> ssl_rsa_kek_source_y = 9a383bf431d0bd8132534ba964397de3
> titlekek_00 = 62a24d6e6d0d0e0abf3554d259be3dc9
> titlekek_01 = 8821f642176969b1a18021d2665c0111
> titlekek_02 = 5d15b9b95a5739a0ac9b20f600283962
> titlekek_03 = 1b3f63bcb67d4b06da5badc7d89acce1
> titlekek_04 = e45c1789a69c7afbbf1a1e61f2499459
> titlekek_05 = ddc67f7189f4527a37b519cb051eee21
> titlekek_06 = b1532b9d38ab036068f074c0d78706ac
> titlekek_07 = 81dc1b1783df268789a6a0edbf058343
> titlekek_08 = 47dfe4bf0eeda88b17136b8005ab08ea
> titlekek_09 = adaa785d90e1a9c182ac07bc276bf600
> titlekek_0a = 42daa957c128f75bb1fda56a8387e17b
> titlekek_source = 1edc7b3b60e6b4d878b81715985e629b
> tsec_key = 7be044e05dc2c6903b068ba4c255a5c5
>

**Comment by deadair3210** [comment]
Either delete or edit your post to remove the keys. They are copyrighted material and the last thing we need is Ninty yelling at us

**Comment by julesontheroad** [comment]
Deleted the keys file. Use the configuration to check if they are detected properly, i imagine they aren't due to probably using linux type end of lines.
Anyway you had more keys than needed.
1.- Use the keyfile checker in the configuration  mode
2.- If they aren't recognize properly take the keys_template.txt and paste the needed keys manually there.
3.- After doing that rename to keys.txt

If that ended not being the issue try using the 32 bits (x86) version, some people have a similar issue with the x64 version, though if it was working fine before and you replaced your key file that might be it.
