### ISSUE TITLE
The program crashes when i try to use multi-pack mode

### ISSUE THREAD

**Issue by Rheluy** [julesontheroad/NSC_BUILDER#123]
(Sorry for my bad english)
Hello, I have been experiencing a crash issue.
When I try to use multi-pack mode, I press 2, but when I press Enter, NSCB just crash. Tried with 2 different versions (0.98b and 0.80) but the same thing occurred.
I don't know what's happening to it to crash all of a sudden, could you help me with it?
Thanks.

**Comment by 7h3Cub3** [comment]
have you tried a fresh install (brand new package from github, nothing in destination folder)? also where do you store it, maybe it's in an area where you need admin rights to be able to write to disk (try not putting it at the root of your system drive for example) or try to start it with admin right to see if it does the same. Got no problem with it so im suspecting something akin to above. Cheers.

**Comment by julesontheroad** [comment]
If you are using the x64 version try with the x86 or python one.
