### ISSUE TITLE
Error message during repacking

### ISSUE THREAD

**Issue by 7h3Cub3** [julesontheroad/NSC_BUILDER#13]
Hello,

I repacked SSBU (smash bros ultimate) with updates and DLC, but for the updates NSP it seems that it give me error message, and the final XCI doesn't work, i repacked alot of games already and this is the only one giving me issue.

Exception: object of type 'NoneType' has no len()

Traceback (most recent call last):
  File "D:\downloads\SWITCH\NSCB\ztools\squirrel.py", line 1748, in <module>
    f.printInfo()
  File "D:\downloads\SWITCH\NSCB\ztools\Fs\Pfs0.py", line 180, in printInfo
    super(Pfs0, self).printInfo( indent)
  File "D:\downloads\SWITCH\NSCB\ztools\Fs\BaseFs.py", line 69, in printInfo
    f.printInfo(indent+1)
  File "D:\downloads\SWITCH\NSCB\ztools\Fs\Nca.py", line 851, in printInfo
    Print.info(tabs + 'key Block: ' + str(hx(key)))
TypeError: a bytes-like object is required, not 'NoneType'

I get this error just after processing of the updates by the tool after the masterkey writing. the game XCI or the DLC NSP don't have this error, only the updates (any of them) 

Packing the game + dlc will work, but if i put any update, the XCI will be not good.

Thanks :)

**Comment by matofesi** [comment]
Same here trying to repack _The First Tree_ with update.

**Comment by matofesi** [comment]
Never mind... You simply need to update your keys.txt :)

**Comment by 7h3Cub3** [comment]
Oh really ? i will try that then, thanks for the tip !

**Comment by matofesi** [comment]
As I see it older nsps show "masterKeyRev =  0x5" when repacking, newer ones show "masterKeyRev =  0x6" and if you don't have *_06 keys you get a "NoneType" error. Updating keys created working xci for me :)

**Comment by 7h3Cub3** [comment]
Make sense, i indeed didn't have the key06 in my key file, i will try and dump them again to see if i can get them.

**Comment by 7h3Cub3** [comment]
Hum nope doesn't seems to work i restarted lockpick with no avail, how did you updated yours ?

**Comment by matofesi** [comment]
Ymmm... I didn't actually updated it myself - I'm way to lazy for that ;)
I simply got current keys package from MaxConsole.

**Comment by 7h3Cub3** [comment]
Oh i will try that then, thanks ^^

**Comment by 7h3Cub3** [comment]
Yup seems to be working fine now, awesome, maybe dev could add a check if it's technically possible and give a message like "you are missing key XXX please add it to keys.txt" or something :)

**Comment by 7h3Cub3** [comment]
Ok closing...
