### ISSUE TITLE
"The game card could not be read, please remove and reinsert it"

### ISSUE THREAD

**Issue by Jayinem** [julesontheroad/NSC_BUILDER#130]
I am trying to add Mortal kombat Aftermath (new dlc) + old dlc + latest update + base game into one XCI. In NSCBuilder I get no errors. It is a large  XCI but 30.4 gb I thought under 32 should work. When I play the game in SXOS it says "The game card could not be read, please remove and reinsert it" Here are my keys

OPTIONAL KEY "xci_header_key" is Missing
aes_kek_generation_source : 4d870986c45d20722fba1053da92e8a9
> HEX SHA256: fc02b9d37b42d7a1452e71444f1f700311d1132e301a83b16062e72a78175085
> Key is valid!!!
aes_key_generation_source : 89615ee05c31b6805fe58f3da24f7aa8
> HEX SHA256: fbd10056999edc7acdb96098e47e2c3606230270d23281e671f0f389fc5bc585
> Key is valid!!!
header_key: aeaab1ca08adf9bef12991f369e3c567d6881e4e4a6a47a51f6e4877062d542d
> HEX SHA256: 8e03de24818d96ce4f2a09b43af979e679974f7570713a61eed8b314864a11d5
> Key is valid!!!
key_area_key_application_source: 7f59971e629f36a13098066f2144c30d
> HEX SHA256: 04ad66143c726b2a139fb6b21128b46f56c553b2b3887110304298d8d0092d9e
> Key is valid!!!
key_area_key_ocean_source: 327d36085ad1758dab4e6fbaa555d882
> HEX SHA256: fd434000c8ff2b26f8e9a9d2d2c12f6be5773cbb9dc86300e1bd99f8ea33a417
> Key is valid!!!
key_area_key_system_source: 8745f1bba6be79647d048ba67b5fda4a
> HEX SHA256: 1f17b1fd51ad1c2379b58f152ca4912ec2106441e51722f38700d5937a1162f7
> Key is valid!!!
master_key_00: c2caaff089b9aed55694876055271c7d
> HEX SHA256: 0ee359be3c864bb0782e1d70a718a0342c551eed28c369754f9c4f691becf7ca
> Key is valid!!!
master_key_01: 54e1b8e999c2fd16cd07b66109acaaa6
> HEX SHA256: 4fe707b7e4abdaf727c894aaf13b1351bfe2ac90d875f73b2e20fa94b9cc661e
> Key is valid!!!
master_key_02: 4f6b10d33072af2f250562bff06b6da3
> HEX SHA256: 79277c0237a2252ec3dfac1f7c359c2b3d121e9db15bb9ab4c2b4408d2f3ae09
> Key is valid!!!
master_key_03: 84e04ec20b9373818c540829cf147f3d
> HEX SHA256: 4f36c565d13325f65ee134073c6a578ffcb0008e02d69400836844eab7432754
> Key is valid!!!
master_key_04: cfa2176790a53ff74974bff2af180921
> HEX SHA256: 75ff1d95d26113550ee6fcc20acb58e97edeb3a2ff52543ed5aec63bdcc3da50
> Key is valid!!!
master_key_05: c1dbedcebf0dd6956079e506cfa1af6e
> HEX SHA256: ebe2bcd6704673ec0f88a187bb2ad9f1cc82b718c389425941bdc194dc46b0dd
> Key is valid!!!
master_key_06: 0aa90e6330cdc12d819b3254d11a4e1e
> HEX SHA256: 9497e6779f5d840f2bba1de4e95ba1d6f21efc94717d5ae5ca37d7ec5bd37a19
> Key is valid!!!
master_key_07: 929f86fbfe4ef7732892bf3462511b0e
> HEX SHA256: 4ec96b8cb01b8dce382149443430b2b6ebcb2983348afa04a25e53609dabedf6
> Key is valid!!!
master_key_08: 23cfb792c3cb50cd715da0f84880c877
> HEX SHA256: 2998e2e23609bc2675ff062a2d64af5b1b78dff463b24119d64a1b64f01b2d51
> Key is valid!!!
master_key_09: 75c93b716255319b8e03e14c19dea64e
> HEX SHA256: 9d486a98067c44b37cf173d3bf577891eb6081ff6b4a166347d9dbbf7025076b
> Key is valid!!!
master_key_10|master_key_0a: 73767484C73088F629B0EEB605F64AA6
> HEX SHA256: 4ec5a237a75a083a9c5f6cf615601522a7f822d06bd4ba32612c9cebbb29bd45
> Key is valid!!!
titlekek_source: 1edc7b3b60e6b4d878b81715985e629b
> HEX SHA256: c48b619827986c7f4e3081d59db2b460c84312650e9a8e6b458e53e8cbca4e87
> Key is valid!!!

So I'm unsure why it won't work. I deleted Mortal Kombat 11 a previous version with all the dlc and update that was new at the time I put it on my external and it works but not this one.

**Comment by deadair3210** [comment]
make sure all the individual parts are not corrupted

**Comment by Jayinem** [comment]
No I figured out it's too large it's 30.4 gb I was thinking you could have 32 gb but a game card is like any other storage it takes like 8% so you can only have 29.xx something gbs.

**Comment by deadair3210** [comment]
Oh yeah I forgot that the switchs os has a max cart size expected
