### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pripri9** [julesontheroad/NSC_BUILDER#131]
when i try to get FM requirements and game info it shows
![image](https://user-images.githubusercontent.com/66540877/83958675-87699780-a86c-11ea-9c67-aa9a5abb1cc4.png)

**Comment by deadair3210** [comment]
make sure you have permission to read and write to the folder that the file is in and the folder that nsc_builder is in

**Comment by julesontheroad** [comment]
Yeah that's 100% permission related the file is probably set as only read, while most functions will only need read permissions if it calls one from nutFs which is possible in that info function it'll also needs write permission even if not writes in the file.
