### ISSUE TITLE
Dumping titles acts as if user did not select anything even if the user did

### ISSUE THREAD

**Issue by Masamune3210** [julesontheroad/NSC_BUILDER#145]
Tried to dump a nsp to test, no matter what i selected or how many, the script returned that I didnt select any

All my issues that I made today are made on the beta branch as of  20eae57, can test on release if needed

![image](https://user-images.githubusercontent.com/1053504/86868458-544c3b00-c09a-11ea-820d-eb263027cf0a.png)

**Comment by julesontheroad** [comment]
You need them selected. The picker module works that way on multipicks, i don't know if i can modify it so if nothing is selected it picks the title you have the cursor on.
![selected](https://user-images.githubusercontent.com/42461174/86892339-695bb500-c100-11ea-8ade-abfb3a5e2c35.PNG)
![dumper](https://user-images.githubusercontent.com/42461174/86892199-387b8000-c100-11ea-8305-db201ee483a2.PNG)

**Comment by Masamune3210** [comment]
I had them selected, both with e and with the right arrow, the program did not notice the selection and acted like I hadnt selected anything

**Comment by julesontheroad** [comment]
hmm, not sure about this one. I don't really see anytghing weird here:
```
def dump_content():
	retrieve_installed()
	installed=get_gamelist()
	print("  * Entering File Picker")	
	title = 'Select content to dump_content: \n + Press space or right to select content \n + Press E to finish selection'
	options=installed
	picker = Picker(options, title, multi_select=True, min_selection_count=1)
	def end_selection(picker):
		return False,-1
	picker.register_custom_handler(ord('e'),  end_selection);picker.register_custom_handler(ord('E'),  end_selection)
	selected=picker.start()
	if selected[0]==False:
		print("    User didn't select any files")
		return False
```
User didn't select any files is only printed if you get **selected[0] as false** selected[0] is the first selected item and in normal conditions is a tupple that's (name of the choice, index of the choice) it should only be False if no files are selected. I can check the picker module but that seems weird.
Is not end selection either since it wouldn't make any prints.

**Comment by Masamune3210** [comment]
I can try again later if you want to make any temp changes that you can think of, at work right now but will gladly beta test

**Comment by Masamune3210** [comment]
Here is a video of the issue, just tested with another switch to make sure it wasnt an issue with mine. Attempting to dump this switch's contents just results in the program acting as if I didnt select anything
https://youtu.be/12cbQ3xpJuI

**Comment by julesontheroad** [comment]
Video is private.

**Comment by Masamune3210** [comment]
Try it now, sorry

https://youtu.be/12cbQ3xpJuI

**Comment by julesontheroad** [comment]
Ok my intuition tells me the error is on my instructions. Selections are entered/finished when you press enter or intro.
In this case the instructions are saying "E" which is the key i use to exit the selection with an empty selection.

I probably pasted the title from the **folder walker** i have on the Drive Mode. That one only shows folders in the first step to make calls to google faster, then you input E and it takes the folder as final, unless it reaches a folder without folders, then either E or the end folder show the files in the folder.

**In all picker functions Enter and Intro are the keys to select files.**

**Comment by Masamune3210** [comment]
Will check after this batch, but I have a feeling you are correct, as I have been pressing E as that's what the instructions make it sound as the last step
