### ISSUE TITLE
Google Drive option in MTP mode does nothing

### ISSUE THREAD

**Issue by Masamune3210** [julesontheroad/NSC_BUILDER#146]
Not sure if known, but the D option in the MTP mode to open Google Drive Modes does nothing, it just repaints the screen

**Comment by julesontheroad** [comment]
did you set the libraries as the changelog says and create the token for your google drive? It works fine on my end. You need:
1.- The service.json in zconfig credentials
2.- To create the token with the config
2.- To setup the remote remote_libraries.txt and remote_cache_location.txt with your locations. 

Then the cache libraries option creates a cache file with the path of your files in each library you set up, the library you set up needs to be a folder with files btw. The other is a direct scrape of google drive and it's filter uses the google search directly.

Also google drive requests may be slow so is adviced to use the cache files normally and regenerate them when you need.

**Comment by julesontheroad** [comment]
If selected the process is:
1.- It asks you for the library
2.- It asks you if you want to add a search filter
3.- It asks you for the order of the files
4.- It shows you the files in the picker. I think you don't have the libraries setup if you don't see the picker.

**Comment by Masamune3210** [comment]
It appears I forgot to set up the libraries required. Maybe a error stating such instead of simply doing nothing?

**Comment by julesontheroad** [comment]
It checks if the txt file doesn't exist but i think it doesn't check for empty list as far as I remember no.
