### ISSUE TITLE
Any way to preserve list on drive full?

### ISSUE THREAD

**Issue by Masamune3210** [julesontheroad/NSC_BUILDER#157]
Currently, when the drive fills, the program will iterate through the rest of the list and error out on each one, which removes it from the list. Any way this could be changed to stop on first drive full error and preserve the list to resume once the error is resolved?

**Comment by Masamune3210** [comment]
Also, dont want to make a new issue for something this small, when installing to the sd card from a computer the string says Swith instead of what I am assuming is supposed to be Switch

![image](https://user-images.githubusercontent.com/1053504/87238244-c5a32b00-c3c5-11ea-9301-5746ee788b1d.png)

**Comment by julesontheroad** [comment]
Yes but that function isn't finished is not added around the whole program and I plan to change the whole workflow of the program after I push the typical bug corrections from 0.99. Second one is noted.
I'm closing the issue since #133 is stil opened.
