### ISSUE TITLE
Dbi author

### ISSUE THREAD

**Issue by rashevskyv** [julesontheroad/NSC_BUILDER#159]
Rashevskyv (it's me) is not an author of dbi. Author's name is duckbill. He is a Russian programmer.

**Comment by julesontheroad** [comment]
I'll change all the references later. Thanks to let me know since I assumed the author was you since I saw you answer questions in github about it. Sorry for the mistake.

**Comment by julesontheroad** [comment]
I think that changes al references, i'll leave it open for a couple of days in case you feel I should change or add anything else to it, i also edited the changelog, the couple of references in the batches will be modified when I push 0.99b. 
Again, sorry for the mistake.

**Comment by rashevskyv** [comment]
No problem :) thank you!

вс, 12 июл. 2020 г., 13:16 julesontheroad <notifications@github.com>:
