### ISSUE TITLE
Files on Network Shares are reported as Directories

### ISSUE THREAD

**Issue by IBNobody** [julesontheroad/NSC_BUILDER#16]
If I have NSP files on a network share such as \\\\foo or have files on a network share with a drive letter mapping (via NET USE) such as S:\\, the method currently being used to detect if a passed path is a file or folder does not work.

I traced the issue down to this line (which is used twice)

`if exist "%bs%\" goto checkfolder`

When this batch string is executed, Windows thinks that the network share NSP file is a folder. It is related to this ancient KB.

https://jeffpar.github.io/kbarchive/kb/065/Q65994/

The workaround is to use dir and errorlevel, which can properly differentiate between network files and folders. Replace the `if exist` lines with...

```
dir "%bs%\" >nul 2>nul
if not errorlevel 1 goto checkfolder
```

**Comment by julesontheroad** [comment]
Thx  for letting me know. I'll take a look into this.

**Comment by IBNobody** [comment]
Fixed! Thank you!
