### ISSUE TITLE
Keep getting "The system cannot find the file list.txt"

### ISSUE THREAD

**Issue by aquaragon** [julesontheroad/NSC_BUILDER#167]
I've updated to the newest NSC_Builder v0.99, and I've dumped latest prod.keys. Whenever I try to repack my xci as nsp's I get this. 

Thanks

**Comment by julesontheroad** [comment]
That means the list.txt wasn't created when you dragged your files. What options did you use? Did you dragged them directly or used a selector option?

**Comment by aquaragon** [comment]
I've tried both. And i've moved the file that I want to folder of nsc_Builder.

**Comment by aquaragon** [comment]
weird just tried again, worked . Thank you so much

**Comment by julesontheroad** [comment]
Ok, closing for now. If you find a weird behaviour on files not being added tell me again. The list function should filter file extensions when adding them so it will add xci, nsp, nsz, xcz, nsx on mode 1 and then it'll filter extensions again depending on the final option you choose. For example the trimmer will only keep xci and xcz or rebuild will only keep nsp and nsz.
