### ISSUE TITLE
File renaming functions incorrectly with some language combonations

### ISSUE THREAD

**Issue by Masamune3210** [julesontheroad/NSC_BUILDER#169]
I've noticed that some files fail to be renamed correctly when it comes to adding the language tags, instead of getting the correct tags, it ends up with the name of the game and then immediately after, a closing )

![image](https://user-images.githubusercontent.com/1053504/87880555-32b35380-c9b8-11ea-9914-e7a2a193c0aa.png)
![image](https://user-images.githubusercontent.com/1053504/87880560-37780780-c9b8-11ea-9bf4-77618c9ad2d8.png)

![image](https://user-images.githubusercontent.com/1053504/87880564-3f37ac00-c9b8-11ea-9fe9-52cd25a4950e.png)
![image](https://user-images.githubusercontent.com/1053504/87880572-4959aa80-c9b8-11ea-932b-051ff2ccf04c.png)

**Comment by julesontheroad** [comment]
I guess something in the filter is eating the tag, would need to check. It may have to do with the filters i apply after romaji since pykashi sometimes adds double spaces or spaces after parenthesis in games that have them.

**Comment by Masamune3210** [comment]
I can find more examples if it would help, I'm sure my database has plenty of then

**Comment by julesontheroad** [comment]
I'm going to rework the renaming after 1.0 anyway. The idea is to allow templating to users if i have time i'll try and check before 1.0 but if not i'll work on it when reworking the renamer, is part of the management stuff.
Next update is mostly more mtp stuff. After that i'll take a pause on mtp to rework several stuff.

**Comment by Masamune3210** [comment]
Ok, let me know if you need help with anything. I'm out of practice with the coding, but I have plenty of spare time and a large dataset to test stuff with!

**Comment by julesontheroad** [comment]
Seems it was related to a a syntax change on newer versions of python, should be fixed now on beta and fix will be added to next release.
