### ISSUE TITLE
issue with some nsp

### ISSUE THREAD

**Issue by KoRnEr007** [julesontheroad/NSC_BUILDER#17]
Hello, i have issue with some NSP (last game i think)

Issue is : Exception non gérée : System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\NSCB\NSCB_temp\secure'.

VERSION 0.79
Dependencies ok 

Exception non gérée : System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\NSCB\NSCB_temp\secure'.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.CommonInit()
   à System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   à System.IO.Directory.GetFiles(String path)
   à hacbuild.HFS0Manager.xci_multiplier(String inDir)
   à hacbuild.Program.Main(String[] args)

I don't know why because, it works with old nsp.

Thanks by advance
Jon

**Comment by julesontheroad** [comment]
Do you have the masterkeys to 0 to 6? I think that error can happen in that case or when a file route has special characters (talking about 0.79)
Also that doesn't seem to be the first error but a consecuence of a previous one. An error happened, nca weren't created, secure folder wasn't created so the program can't find secure folder when it arreives to xci building.
