### ISSUE TITLE
problems with NSCB_config.bat

### ISSUE THREAD

**Issue by shadow2560** [julesontheroad/NSC_BUILDER#18]
Hi,

I think the NSCB_config.bat file is not correctly configured because you've added a new config param in the last version but the rest has not been updated. For example, (%pycommand% "%listmanager%" -rl "%op_file%" -ln "116" -nl "SD File Format is set to: ") is not correct because this line doesn't point the good configuration line and I think these type of lines must be fixed, also probably when the script set the configuration lines.

**Comment by julesontheroad** [comment]
116+1=117 sinceramente Python listing starts by 0. 
117 = set "fatype=-fat exfat"
That's correcto. Te configuration file was wrong because i didn't edites all 4 lines that's changes between the exe versions and Python versions bit I corected that after

**Comment by julesontheroad** [comment]
just redownloaded the last release and the config is pointing correctly to the intended lines. Is currently getting the intended values in the 3 versions:
![configuration](https://user-images.githubusercontent.com/42461174/53861560-d202c100-3fe4-11e9-90de-3b6d5729eeac.JPG)

**Comment by shadow2560** [comment]
OK, that's good, thanks for the quick answer, I close the issue.
