### ISSUE TITLE
squirrel.exe in 0.99 and later version can't create list.txt file when using file selector

### ISSUE THREAD

**Issue by zdm65477730** [julesontheroad/NSC_BUILDER#183]
In v0.99 and later verison, if we choose file by manual not drag the file, the list.txt can't be created.
I checked it in 0.98, it works well, and I replace the squirrel.exe file in v0.98 to v0.99/v1.00, it works as well.

So, there is something wrong in latest version of squirrel.ext(a.k.a nut?).

**Comment by julesontheroad** [comment]
This should fix it. I don't know when i modified it but i left it incomplete and my intention was probably do the same as the Interface.
Basically prefilter the allowed extensions when in file mode. That adds that and also solves the issue.

**Comment by julesontheroad** [comment]
Is fixed with https://github.com/julesontheroad/NSC_BUILDER/releases/tag/1.00d you can ignore the bats, i just updated the version to d on them.
