### ISSUE TITLE
 issue with dlc

### ISSUE THREAD

**Issue by goooodlife** [julesontheroad/NSC_BUILDER#19]
Hello, i have issue with [DLC][010050000705F012][v0].nsp（keygeneration:7）
my switch is reinx 6.1 
Made a keygeneration:6 dlc , but after installing with tilfoil 
As soon as I start the game, I will issue a [Unplayable downloadable content was found] warning message.
dlc can't convert successfully?

**Comment by julesontheroad** [comment]
That's normal when you remove, touch or make a dlc from 6.0. The dlc will work fine even if the message is shown. It seems like an integrity check but doesn't impede the dlc to work.
What I think is that is related to updates, and it doesn't seem to happen with all dlcs but i didn't looked into it really. It's bothersome but your dlc should work fine.

**Comment by goooodlife** [comment]
I understand，thanks for your answer
