### ISSUE TITLE
Is there a way to check if an NSP has been converted from an XCI 

### ISSUE THREAD

**Issue by kbachtal** [julesontheroad/NSC_BUILDER#193]
I apologize in advance if this is a stupid question or this is not the right place to be asking, but is there a way to check if an NSP has been converted from an XCI and can it be done as a batch?

**Comment by WanderMax** [comment]
if nsp is from shop, nscb and hactool verification will pass, as it has Nintendo signature. if nsp is converted by nscb, nscb verification will pass, hactool verification will fail, as no Nintendo signature.
if nsp isconverted by other tool, all verification fail.
maybe nscb can recognize its converted nsp file.

**Comment by Masamune3210** [comment]
as far as i remember, nsc_builder can tell you if IS_GAMECARD was set to 1 originally if you check the info of a file

**Comment by kbachtal** [comment]
Thank you to everyone for the very prompt responses. Masamune3210, you are correct. I did a mass verify and when I checked the *-verify.txt's anything that had been converted from and XCI showed: "* ISGAMECARD WAS CHANGED FROM 1 TO 0". Again thank you to everyone for the responses and sorry to take up valuable developer time. BTW great job, NSC_BUILDER is an awesome utility.
