### ISSUE TITLE
CLI resets on error

### ISSUE THREAD

**Issue by jmhg92** [julesontheroad/NSC_BUILDER#194]
When using the verification tool under FILE-INFO on some NSP fles there seems to be an error, but the error is shown very briefly (perhaps a few milliseconds) that you can't see it and you are sent back to the FILE-INFO options. It would be better if the error showed and paused for user input to see what the error was.

Also, it would be great if there was an option to output errors to a log file instead, maybe with some debugging info like filename and error to help find the root cause of the problem.

I'm using version 1.00d but this problem has also occurred in previous versions.

EDIT
----

**Steps to reproduce**

1. Start NSCB.bat
2. `Input "4"  to enter into FILE-INFO mode`
3. Drag NSP file
4. `Input "8" to VERIFY file (xci\nsp\nsx\nca)`
5. `Input "1" to VERIFY hash of files`
6. The screen goes back to the `FILE-INFO` options

**Comment by Masamune3210** [comment]
If you use option 8, the verify files function, it will make a file called badfiles.txt with all the files and the errors about them

**Comment by jmhg92** [comment]
> If you use option 8, the verify files function, it will make a file called badfiles.txt with all the files and the errors about them

I have searched for this file and I don't see it anywhere.

The problem happens when I select option 1 `VERIFY hash of files` after getting a `VERDICT: NSP FILE COULD'VE BEEN TAMPERED WITH` after the first verification. Some files that get this veredict can still be checked via hash but others just seem to get an error and sends me back to the "FILE-INFO" options without the usual prompt to save output to a file.

**Comment by Masamune3210** [comment]
If you are using the batch file included, its option 8 on the start, you select it, then feed it whatever files you want checked, then it gives you a bunch of options on how and what to check

**Comment by jmhg92** [comment]
> If you are using the batch file included, its option 8 on the start, you select it, then feed it whatever files you want checked, then it gives you a bunch of options on how and what to check

Option 8 from the start is `Compression\Decompression` mode according to the README. I'm talking about option 8 inside the `FILE-INFO` mode.

I have edited my original report with the steps to reproduce the error

**Comment by Masamune3210** [comment]
I goofed, its option 8 after option 1

**Comment by jmhg92** [comment]
> I goofed, its option 8 after option 1

I have tried it with a file that gives the error and i get the following:

`Exception: local variable 'listedhash' referenced before assignment`

I also tried it with another file and there is no exception thrown. So my guess is that this exception is thrown in the FILE-INFO verification process but it's displayed for a few millisenconds before sending me back to the options screen

**Comment by julesontheroad** [comment]
each file log goes into a info folder on the NSCB main folder. I think is INFO/MASSVERIFY. The badfiles is shown only when some file returns a bad verification.
Not sure in what scenario the listedhash can be referenced before asignment but i'll try to fix it. I'm quite busy later but a lot of things are planed to change after the rework, for example every function under 1 now has it's own file list, and i was also planing to add more stuff to the verification but i didn't have time lately to code stuff.

**Comment by julesontheroad** [comment]
didn't managed to reproduce the issue
