### ISSUE TITLE
Corruption when building XCI (again) with NSCB latest version (v1.00d)

### ISSUE THREAD

**Issue by doctahoo** [julesontheroad/NSC_BUILDER#195]
Hi,

This happened again, this time with Super Mario 3D All-Stars NSP + update v65536. Is the resulting XCI file reliable or not?

***************
DECRYPTION TEST
***************
010049900F546000 - Content.PROGRAM
	6bda1c789b220d50d1e84a4e7444483a.nca	  -> is CORRECT
010049900F546000 - Content.CONTROL
	4057dd04dfad17ac15e0d6f6855ceb58.nca	  -> is CORRECT
010049900F546000 - Content.MANUAL
	98dc89e78cfa717e1977986de3677fff.nca	  -> is CORRECT
010049900F546000 - Content.MANUAL
	8ec6ca0494636e7049c7014264a0300e.nca	  -> is CORRECT
010049900F546001 - Content.PROGRAM
	c603ea332457144e47d1d7988e4a1c21.nca	  -> is CORRECT
010049900F546001 - Content.CONTROL
	72b0cdc4fc7952c3a574e9a25f808507.nca	  -> is CORRECT
010049900F546001 - Content.MANUAL
	9a806519ba2164c4aeb433a2c4ec0bb3.nca	  -> is CORRECT
010049900F546002 - Content.PROGRAM
	a27eba379c19de9e9da9b4410fb9c330.nca	  -> is CORRECT
010049900F546002 - Content.CONTROL
	2551b21b3d5d8581255db2c221a71dc4.nca	  -> is CORRECT
010049900F546002 - Content.MANUAL
	c96cff79fb58065a4c4f75332d528336.nca	  -> is CORRECT
010049900F546003 - Content.PROGRAM
	f66a210636e595b875010cdfb2e88186.nca	  -> is CORRECT
010049900F546003 - Content.CONTROL
	a74a62e709ffd4a843e47c68051504bd.nca	  -> is CORRECT
010049900F546003 - Content.MANUAL
	78f18454b1bd169f77b7c3d4b2e1c453.nca	  -> is CORRECT
010049900F546000 - Content.META
	867596e19cf12cf6b1b1d6e7628bf9c1.cnmt.nca -> is CORRECT
010049900F546000 - Content.PROGRAM
	6c1b08e3197f55e65affb0250446ab58.nca	  -> is CORRECT
010049900F546000 - Content.CONTROL
	7ed241d1373097e00d2ab4301b599a4e.nca	  -> is CORRECT
010049900F546000 - Content.MANUAL
	0b7aa334be7215b6d7cfc5f417c9a8fa.nca	  -> is CORRECT
010049900F546000 - Content.MANUAL
	0471acf43f7faff5fc83227a8a47e5e1.nca	  -> is CORRECT
010049900F546001 - Content.PROGRAM
	09ead702b926829ffbc7da03dd238958.nca	  -> is CORRECT
010049900F546001 - Content.CONTROL
	f89220a81a3819957576d0371c9418c7.nca	  -> is CORRECT
010049900F546001 - Content.MANUAL
	9ff6fc22a9174bee8f9c5d5736ca691d.nca	  -> is CORRECT
010049900F546002 - Content.PROGRAM
	82957f8259014bbb16ceaf1ad9359136.nca	  -> is CORRECT
010049900F546002 - Content.CONTROL
	7f82f93513947adaac3e373e9eb07dd6.nca	  -> is CORRECT
010049900F546002 - Content.MANUAL
	1e10290728c5e40b06d420f814fb3a1d.nca	  -> is CORRECT
010049900F546003 - Content.PROGRAM
	8e5b28120dadbe74e54bf740606b2f95.nca	  -> is CORRECT
010049900F546003 - Content.CONTROL
	ccfe0de5e9b71b1a72e4a4f40c74a0d4.nca	  -> is CORRECT
010049900F546003 - Content.MANUAL
	255da8307abfa598f3b5c740c06e8ff2.nca	  -> is CORRECT
010049900F546800 - Content.META
	98f02e2f1b3072b42cffd0f3c0df9039.cnmt.nca -> is CORRECT

VERDICT: XCI FILE IS CORRECT

****************
SIGNATURE 1 TEST
****************
010049900F546000 - Content.PROGRAM
    > 6bda1c789b220d50d1e84a4e7444483a.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546000000000000000000B
	* Original titlekey is       : A6A5141D9A1FC44F57BD6138E5D18163

010049900F546000 - Content.CONTROL
    > 4057dd04dfad17ac15e0d6f6855ceb58.nca	  -> is PROPER

010049900F546000 - Content.MANUAL
    > 98dc89e78cfa717e1977986de3677fff.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546000000000000000000B
	* Original titlekey is       : A6A5141D9A1FC44F57BD6138E5D18163

010049900F546000 - Content.MANUAL
    > 8ec6ca0494636e7049c7014264a0300e.nca	  -> is PROPER

010049900F546001 - Content.PROGRAM
    > c603ea332457144e47d1d7988e4a1c21.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546000000000000000000B
	* Original titlekey is       : A6A5141D9A1FC44F57BD6138E5D18163

010049900F546001 - Content.CONTROL
    > 72b0cdc4fc7952c3a574e9a25f808507.nca	  -> is PROPER

010049900F546001 - Content.MANUAL
    > 9a806519ba2164c4aeb433a2c4ec0bb3.nca	  -> was MODIFIED
	* NOT VERIFIABLE COULD'VE BEEN TAMPERED WITH

010049900F546002 - Content.PROGRAM
    > a27eba379c19de9e9da9b4410fb9c330.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546000000000000000000B
	* Original titlekey is       : A6A5141D9A1FC44F57BD6138E5D18163

010049900F546002 - Content.CONTROL
    > 2551b21b3d5d8581255db2c221a71dc4.nca	  -> is PROPER

010049900F546002 - Content.MANUAL
    > c96cff79fb58065a4c4f75332d528336.nca	  -> was MODIFIED
	* NOT VERIFIABLE COULD'VE BEEN TAMPERED WITH

010049900F546003 - Content.PROGRAM
    > f66a210636e595b875010cdfb2e88186.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546000000000000000000B
	* Original titlekey is       : A6A5141D9A1FC44F57BD6138E5D18163

010049900F546003 - Content.CONTROL
    > a74a62e709ffd4a843e47c68051504bd.nca	  -> is PROPER

010049900F546003 - Content.MANUAL
    > 78f18454b1bd169f77b7c3d4b2e1c453.nca	  -> was MODIFIED
	* NOT VERIFIABLE COULD'VE BEEN TAMPERED WITH

010049900F546000 - Content.PROGRAM
    > 6c1b08e3197f55e65affb0250446ab58.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546000 - Content.CONTROL
    > 7ed241d1373097e00d2ab4301b599a4e.nca	  -> is PROPER

010049900F546000 - Content.MANUAL
    > 0b7aa334be7215b6d7cfc5f417c9a8fa.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546000 - Content.MANUAL
    > 0471acf43f7faff5fc83227a8a47e5e1.nca	  -> is PROPER

010049900F546001 - Content.PROGRAM
    > 09ead702b926829ffbc7da03dd238958.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546001 - Content.CONTROL
    > f89220a81a3819957576d0371c9418c7.nca	  -> is PROPER

010049900F546001 - Content.MANUAL
    > 9ff6fc22a9174bee8f9c5d5736ca691d.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546002 - Content.PROGRAM
    > 82957f8259014bbb16ceaf1ad9359136.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546002 - Content.CONTROL
    > 7f82f93513947adaac3e373e9eb07dd6.nca	  -> is PROPER

010049900F546002 - Content.MANUAL
    > 1e10290728c5e40b06d420f814fb3a1d.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546003 - Content.PROGRAM
    > 8e5b28120dadbe74e54bf740606b2f95.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546003 - Content.CONTROL
    > ccfe0de5e9b71b1a72e4a4f40c74a0d4.nca	  -> is PROPER

010049900F546003 - Content.MANUAL
    > 255da8307abfa598f3b5c740c06e8ff2.nca	  -> is PROPER
	* TITLERIGHTS WERE REMOVED
	* Original titlerights id is : 010049900F546800000000000000000B
	* Original titlekey is       : 9C3BB2B747D3804791492C37A706E8EC

010049900F546000 - Content.META
    > 867596e19cf12cf6b1b1d6e7628bf9c1.cnmt.nca   -> is PROPER

010049900F546800 - Content.META
    > 98f02e2f1b3072b42cffd0f3c0df9039.cnmt.nca   -> is PROPER

VERDICT: XCI FILE COULD'VE BEEN TAMPERED WITH

***************
HASH TEST
***************
010049900F546000 - Content.PROGRAM
  - File name: 6bda1c789b220d50d1e84a4e7444483a.nca
  - SHA256: b892fcd4430db4f255ca3a1a00ef5f7d51be47b45138d6dc7923a5382667700e
  - ORIG_SHA256: 6bda1c789b220d50d1e84a4e7444483abdd2a33af7ee555fc1b22a52e64e4aff
   > FILE IS CORRECT

010049900F546000 - Content.CONTROL
  - File name: 4057dd04dfad17ac15e0d6f6855ceb58.nca
  - SHA256: 4057dd04dfad17ac15e0d6f6855ceb58d6b50b35ae6eb602b8bd7a124845b530
   > FILE IS CORRECT

010049900F546000 - Content.MANUAL
  - File name: 98dc89e78cfa717e1977986de3677fff.nca
  - SHA256: e5459f5748cfc0a350cd29b484ff02bc38d2a599458d77e2a95f0a7fc8119300
  - ORIG_SHA256: 98dc89e78cfa717e1977986de3677fffbabd57db13134dbfc3cbb386e6bc8967
   > FILE IS CORRECT

010049900F546000 - Content.MANUAL
  - File name: 8ec6ca0494636e7049c7014264a0300e.nca
  - SHA256: 8ec6ca0494636e7049c7014264a0300e693329ae67a2a558fce77d0fddfc4b87
   > FILE IS CORRECT

010049900F546001 - Content.PROGRAM
  - File name: c603ea332457144e47d1d7988e4a1c21.nca
  - SHA256: 8c05f1b1806bc68be6e24545a0cccb9940240dec70eb579d0b492ed7da9d3f3d
  - ORIG_SHA256: c603ea332457144e47d1d7988e4a1c212f06c70b71df56c36e621fbb4976b03c
   > FILE IS CORRECT

010049900F546001 - Content.CONTROL
  - File name: 72b0cdc4fc7952c3a574e9a25f808507.nca
  - SHA256: 72b0cdc4fc7952c3a574e9a25f808507db2f4fdb416cd45e7037035ad0551bd3
   > FILE IS CORRECT

010049900F546001 - Content.MANUAL
  - File name: 9a806519ba2164c4aeb433a2c4ec0bb3.nca
  - SHA256: cc7ba9b4c59fe8942770f5730a15f44368aa7f40407e31e8499e9429d0c9824b
   > FILE IS CORRUPT

010049900F546002 - Content.PROGRAM
  - File name: a27eba379c19de9e9da9b4410fb9c330.nca
  - SHA256: 74090f4c11436e5b3ccdd7f7fb549ff7fd862d33d10d4b10fba5c0eb4efdc75b
  - ORIG_SHA256: a27eba379c19de9e9da9b4410fb9c33024fe8fa04307821c624a3e0b8276f138
   > FILE IS CORRECT

010049900F546002 - Content.CONTROL
  - File name: 2551b21b3d5d8581255db2c221a71dc4.nca
  - SHA256: 2551b21b3d5d8581255db2c221a71dc47f9bd6b802d61622f7351c2082178347
   > FILE IS CORRECT

010049900F546002 - Content.MANUAL
  - File name: c96cff79fb58065a4c4f75332d528336.nca
  - SHA256: abc6d0c26322a61eb0f8128b0a0dd6478c7ef4fb6e67f27255e0f84f56bb625f
   > FILE IS CORRUPT

010049900F546003 - Content.PROGRAM
  - File name: f66a210636e595b875010cdfb2e88186.nca
  - SHA256: 36ff780e11ba3a1b42884c9b1e2d762215c4f8a126339ba99f8ebd8b502ddbea
  - ORIG_SHA256: f66a210636e595b875010cdfb2e8818616e040c963a7801a6ed96ef0b4fa02ad
   > FILE IS CORRECT

010049900F546003 - Content.CONTROL
  - File name: a74a62e709ffd4a843e47c68051504bd.nca
  - SHA256: a74a62e709ffd4a843e47c68051504bdc058aa319062cd8c1eeab5ddfc5a429e
   > FILE IS CORRECT

010049900F546003 - Content.MANUAL
  - File name: 78f18454b1bd169f77b7c3d4b2e1c453.nca
  - SHA256: 736b18e8489f17e1b600fa59fa63c1cd584b070d50c4b877c15de40b4a4aabcd
   > FILE IS CORRUPT

010049900F546000 - Content.META
  - File name: 867596e19cf12cf6b1b1d6e7628bf9c1.cnmt.nca
  - SHA256: 867596e19cf12cf6b1b1d6e7628bf9c1e6a15adf8b634cfe9952565957b731c2
   > FILE IS CORRECT

010049900F546000 - Content.PROGRAM
  - File name: 6c1b08e3197f55e65affb0250446ab58.nca
  - SHA256: 1d2cad2e01005460df581a939a991d7f1f99c5e3c97d51cc5f86c44e8eb3b366
  - ORIG_SHA256: 6c1b08e3197f55e65affb0250446ab5819690c4a9cc55e1bc0dc9d866fd42b92
   > FILE IS CORRECT

010049900F546000 - Content.CONTROL
  - File name: 7ed241d1373097e00d2ab4301b599a4e.nca
  - SHA256: 7ed241d1373097e00d2ab4301b599a4e01d2561767b5f9ebcbffd1a1b3fc61ce
   > FILE IS CORRECT

010049900F546000 - Content.MANUAL
  - File name: 0b7aa334be7215b6d7cfc5f417c9a8fa.nca
  - SHA256: d9950b6ad6e1d1d7965d3c51efd41cf69a3dd5ed74427b3cceae2ca46d8cb526
  - ORIG_SHA256: 0b7aa334be7215b6d7cfc5f417c9a8fa1f2aa70bd69f58cb5e188aa86f14926b
   > FILE IS CORRECT

010049900F546000 - Content.MANUAL
  - File name: 0471acf43f7faff5fc83227a8a47e5e1.nca
  - SHA256: 0471acf43f7faff5fc83227a8a47e5e13ba4f69613c6bdeded1305f2eb1582af
   > FILE IS CORRECT

010049900F546001 - Content.PROGRAM
  - File name: 09ead702b926829ffbc7da03dd238958.nca
  - SHA256: 85dbecd5dd9392962b310af537f7399a11ab9f3e1fbae2901d9bba390e0aeb09
  - ORIG_SHA256: 09ead702b926829ffbc7da03dd238958970ffb81993979b214d583a0a1858940
   > FILE IS CORRECT

010049900F546001 - Content.CONTROL
  - File name: f89220a81a3819957576d0371c9418c7.nca
  - SHA256: f89220a81a3819957576d0371c9418c78aa39ecb516cec7fb8ef9769a396a1bd
   > FILE IS CORRECT

010049900F546001 - Content.MANUAL
  - File name: 9ff6fc22a9174bee8f9c5d5736ca691d.nca
  - SHA256: c9420a0cd92a7639f8d05f6be5fed09c6818f9d99d4c2f18e56568463c92ffcd
  - ORIG_SHA256: 9ff6fc22a9174bee8f9c5d5736ca691d3e63ff9de19a52aced45d31ad29ff7a4
   > FILE IS CORRECT

010049900F546002 - Content.PROGRAM
  - File name: 82957f8259014bbb16ceaf1ad9359136.nca
  - SHA256: 7dad46711e83728cf67091424d9c92a908589433f13050ed4577889b47c053d3
  - ORIG_SHA256: 82957f8259014bbb16ceaf1ad9359136209b2a518d810887a9acd90a74bea2fa
   > FILE IS CORRECT

010049900F546002 - Content.CONTROL
  - File name: 7f82f93513947adaac3e373e9eb07dd6.nca
  - SHA256: 7f82f93513947adaac3e373e9eb07dd646b1beb147e2bece30ebac64c5e66775
   > FILE IS CORRECT

010049900F546002 - Content.MANUAL
  - File name: 1e10290728c5e40b06d420f814fb3a1d.nca
  - SHA256: 7ab9248eb2467f83f967cae11139fdb98a375f7d31facc0a590ed1b5f67bef61
  - ORIG_SHA256: 1e10290728c5e40b06d420f814fb3a1d334c863de454d5f64f638f50dace93be
   > FILE IS CORRECT

010049900F546003 - Content.PROGRAM
  - File name: 8e5b28120dadbe74e54bf740606b2f95.nca
  - SHA256: b10862c0b78a85af6d14ddb57682c848217f338890630b6d32f06652e80e3dd6
  - ORIG_SHA256: 8e5b28120dadbe74e54bf740606b2f95ebff838621079d9d6a2ef1bbe714ac4b
   > FILE IS CORRECT

010049900F546003 - Content.CONTROL
  - File name: ccfe0de5e9b71b1a72e4a4f40c74a0d4.nca
  - SHA256: ccfe0de5e9b71b1a72e4a4f40c74a0d4cd9cedb49101d03f9197e445e8edd6da
   > FILE IS CORRECT

010049900F546003 - Content.MANUAL
  - File name: 255da8307abfa598f3b5c740c06e8ff2.nca
  - SHA256: 4164dd08952777d38a6c6cb3f8628ac02ef225e735f2efbc7550c57f9b97071d
  - ORIG_SHA256: 255da8307abfa598f3b5c740c06e8ff225b992eb98e294c653fe98212a2723ec
   > FILE IS CORRECT

010049900F546800 - Content.META
  - File name: 98f02e2f1b3072b42cffd0f3c0df9039.cnmt.nca
  - SHA256: 98f02e2f1b3072b42cffd0f3c0df90398bc033d27c8d6f89c26680203da65e9e
   > FILE IS CORRECT

VERDICT: XCI FILE IS CORRUPT

**Comment by julesontheroad** [comment]
That's a verification error i fixed it on the beta. I think is related to one change done before for multiprogram. When i did the change i forgot to apply it to html manuals too since they are also encrypted with the ticket. The file should be ok but it has that verification error.
I think is this fix https://github.com/julesontheroad/NSC_BUILDER/commit/4cd89011f194d4f302b1945539562762616c168e
The titlerights will end by 000 even if the program.
I wanted to add the dbi changes but in case i don't have time i may build the exes reflecting the changes on the beta tomorrow.
In my case i just verify the All Stars Game+Update and is passing verifications.

**Comment by doctahoo** [comment]
OK. Thank you! Waiting for your next build then.

**Comment by julesontheroad** [comment]
Final build will be probably up on a couple of days since some stuff i changing on the mtp support needs some testing,

**Comment by julesontheroad** [comment]
With the new release we can close this issue:
https://github.com/julesontheroad/NSC_BUILDER/releases/tag/1.01
