### ISSUE TITLE
Won't work on Linux with Python

### ISSUE THREAD

**Issue by bleszerd** [julesontheroad/NSC_BUILDER#207]
I tried to run NSCB on Linux (EndeavourOS) with python and received this error:

**[bleszerd@EndeavourOS ztools]$** sudo python ./squirrel.py -lib_call Interface start
_Exception:_ No module named 'oauth2client'

**Comment by eku** [comment]
Install ```python3-oauth2client``` package.

**Comment by bleszerd** [comment]
I also tried this before, but I always get a different error message. I installed all the packages and if I remember correctly, python complained about a module called "slimpath" that I couldn't solve
I ended up doing dual boot, or I could have solved it with a virtual machine.

**Comment by julesontheroad** [comment]
This should do the trick:
https://github.com/julesontheroad/NSC_BUILDER/commit/3574664255aa57ec686ef33050d0757ba32ff529

**Comment by bleszerd** [comment]
Forgive me, I'm totally a layman with python.
![Captura de tela de 2020-10-29 11-10-31](https://user-images.githubusercontent.com/54445836/97585070-7e25c680-19d7-11eb-9d79-810774da3bef.png)

**Comment by bleszerd** [comment]
Terminal log:
[squirrel.log](https://github.com/julesontheroad/NSC_BUILDER/files/5458937/squirrel.log)
