### ISSUE TITLE
nsp converted to xci won't load on SXOS (but will install)

### ISSUE THREAD

**Issue by neFAST** [julesontheroad/NSC_BUILDER#22]
Hello, title says it all.
I have converted nsp to xci in automatic "drag and drop mode".
SXOS shows an error saying that it failed to read the cartridge but it can install it just fine.

Any idea what I did wrong?

**Comment by julesontheroad** [comment]
Did any error prompt during the building process? Something in the xci header could be wrong and that's why it installs but doesn't load. 
If you can give me more data that would be helpfull. Another helpfull thing would be to test building it with 0.80-c

**Comment by neFAST** [comment]
@julesontheroad this is what I get:
`Generating XCI:
rightsId =      0x1002cd00a51c0000000000000000007
titleKeyDec =   b'cb69a0c614033d816f1454070860a0db'
masterKeyRev =  0x7

        - Writing XCI header...
        - Writing XCI game info...
        - Generating padding...
        - Writing XCI certificate...
        - Writing ROOT HFS0 header...
        - Writing UPDATE partition header...
          Calculated multiplier: 1
        - Writing NORMAL partition header...
          Calculated multiplier: 1
        - Writing SECURE partition header...
          Calculated multiplier: 1

        * Appending: 6002daa36b3e98a7017c30ad730edd49.nca

        * Appending: 8ebffd707f176c3f5e67590c873aadc0.nca

        * Getting: a6a2e1ee73755d02738b3d15069e6d1e.cnmt.nca
        - Appending: a6a2e1ee73755d02738b3d15069e6d1e.cnmt.nca

        * Appending: 024b7cf9d543734e7337afc43a83416a.nca

Closing file. Please wait
`

**Comment by neFAST** [comment]
Ok, so with v0.80-c it loads fine!

**Comment by julesontheroad** [comment]
I'll try tomorrow with Baba and see if i can detect the issue. 0.81 has changes in the individual building and splitter mode to do the building without extraction and cut times, that's why it's a beta since i had to rebuild the entire function.
Apparently it seems that it isn't removing the titlerights for some reason.

**Comment by julesontheroad** [comment]
This should be solved currently
