### ISSUE TITLE
Wrong Option Name in 'Req System Version' Configuration Menu

### ISSUE THREAD

**Issue by lahma69** [julesontheroad/NSC_BUILDER#23]
Release: "NSC_BUILDER BETA v0.81-d" (I'm using x64 version specifically)
Under 'AUTO MODE - Configuration', there is an incorrectly named menu item when you select the option:
> Input "3" to change RSV patching configuration

The 1st option is displayed correctly, but the string for the 2nd option is clearly incorrect (looks like a string from the "repacking" config menu). Its probably easiest to just copy/paste the menu to show what I'm referring to:

> Patches the RequiredSystemVersion so console doesn't ask for updates bigger
the required FW to decypher the crypto
> 
> Input "1" to patch Required System Version in the meta nca
> **Input "2" to repack folder's files together (multi-content file)**
> 
> Input "b" to return to AUTO-MODE - CONFIGURATION
> Input "0" to return to CONFIG MENU
> Input "e" to go back to the MAIN PROGRAM

No biggie, but I just thought I'd point it out.

**Comment by julesontheroad** [comment]
Ah thanks I missed that one, i'll fix it trough the weekend. It must've been wrong for a long time XD

**Comment by lahma69** [comment]
No problem! Let me know once you've pushed out a fix and I'll close the issue.

**Comment by julesontheroad** [comment]
This is currently fixed since some versions ago.
