### ISSUE TITLE
"fexport=-fx folder" is splitting as files (not as a folder)

### ISSUE THREAD

**Issue by lahma69** [julesontheroad/NSC_BUILDER#24]
Release: "NSC_BUILDER BETA v0.81-d" (I'm using x64 version specifically)
Whenever the following config option is set as follows, the app is outputting split XCI files (xc0, xc1, xc2, etc) instead of outputting to an archive folder (with files inside such as 00, 01, 02, etc).

> set "fatype=-fat fat32"
> set "fexport=-fx folder"

As I understand it, this should only be happening if the config is set as follows, right?

> set "fatype=-fat fat32"
> set "fexport=-fx files"

**Comment by julesontheroad** [comment]
that's what's intended to do. When exporting to nsp it can export as archive folder or files but when exporting as xci it'll export as files.
xci files are always loaded as files for nsp the only reason to choose folder is if you're not using SX OS in my opinion.
If you export to nsp you should get the folder with archive files.

**Comment by lahma69** [comment]
Interesting... I definitely was not aware that the "folder" setting applied to nsp output only. Thanks for letting me know. Great tool!
