### ISSUE TITLE
Multi-Pack Mode (option 2) fails to create a multi-content .xci file in latest NSCB v0.81-d BETA 2

### ISSUE THREAD

**Issue by doctahoo** [julesontheroad/NSC_BUILDER#25]
Hi,

After trying your latest x64 and x32 versions of NSCB v0.81-d BETA 2 from the master page with a game (Captain Toad base game + 2 DLCs + 1 update), the resulting .xci file contains only DLC1, and has a file size of 279,762 KB instead of the expected size of 1,909,574 KB). This does not happen in NSCB v0.80-c.

Something seems to prevent adding all 4 files correctly. See files attached:

[Display Text 1.txt](https://github.com/julesontheroad/NSC_BUILDER/files/2999920/Display.Text.1.txt)
[Display Text 2.txt](https://github.com/julesontheroad/NSC_BUILDER/files/2999921/Display.Text.2.txt)

**Comment by julesontheroad** [comment]
Yeah there is some people that seems  to have issues with the way the multi mode is taking directly items from the list. I have a new function to replace the multi mode and build in one go like the individual mode does now, it also creates a file with the newer version of content it'll take still some days to add support for all the current patches to that function though.
For now keep using https://github.com/julesontheroad/NSC_BUILDER/releases/tag/v0.80-c for multis.

**Comment by julesontheroad** [comment]
This should be solved currently
