### ISSUE TITLE
Switch to Python only

### ISSUE THREAD

**Issue by marvinroger** [julesontheroad/NSC_BUILDER#26]
Hi,

Thanks for the great tool! I am just wondering, do you consider switching to Python only, removing all batch dependencies?

That would be a great step forward as it would allow the tool to be used on Mac and Linux.

**Comment by julesontheroad** [comment]
Yeah that's the intention but i'm still working in finishing the program. I intend to add direct multi xci and nsp creation before i start working in a full python solution.

**Comment by marvinroger** [comment]
Awesome! Thanks for the answer. 😉

**Comment by mbirth** [comment]
And please split it up into multiple small manageable scripts instead of one huge all-in-one-spaghetti-code file.

**Comment by Kinstono** [comment]
CLI version for linux would be a great

**Comment by station7** [comment]
+1 for a Linux CLI version

**Comment by iexa** [comment]
yeah +1 for linux / macos cli in python. i might take a look a more closer look at these windows batch files, just out of curiosity.

**Comment by spling-du-futur** [comment]
for the linux i think you can use dosbox/wine
