### ISSUE TITLE
Can process individual files (option 1) but cant do multi-content xci (option 2)

### ISSUE THREAD

**Issue by Agent-No-7** [julesontheroad/NSC_BUILDER#28]
I can use option 1 to process, repackage, patch, etc. No issues. However, if i try to multipack i get error 22., keys.txt are missing (only in multipack) and system cannot find path/file specified errors. After that it pops out a 62kb junk file in the output folder. is there a fix for this or is this all user error?

**Comment by julesontheroad** [comment]
Can you try with last version?
