### ISSUE TITLE
support for mac?

### ISSUE THREAD

**Issue by rikimm** [julesontheroad/NSC_BUILDER#29]
They think to take support for mac?

**Comment by iexa** [comment]
Better yet, use only python instead of windows batch scripts. Then it will be compatible with linux/osx/windows. Having to set up docker or wine or a vm for this is overkill.

**Comment by azoreseuropa** [comment]
Nice tool but will it support for macOS users ?

**Comment by staniki** [comment]
Nice app, but not support macOS :(
