### ISSUE TITLE
Converting an NSP to XCI gives me a plethora of "permission denieds."

### ISSUE THREAD

**Issue by nanashi89** [julesontheroad/NSC_BUILDER#3]
![untitled](https://user-images.githubusercontent.com/23020427/48228398-0f2aaf80-e373-11e8-8b4b-4e5456506418.png)

**Comment by julesontheroad** [comment]
Counter in multimode use **set "cmd=findstr /R /N "^^" "%~dp0mlist.txt" | find /C ":""**
where      **/C        Count the number of lines containing the string.**
seems in your case your system uses **"/"** instead of **" \"** for folder routes what seems to cause your issue.

**Comment by julesontheroad** [comment]
I just put in next release **NSCB_test.bat** wich has the counter commented. I won't show you the number of files that remain to be process but shouldn't try to search your drive.
[NSCB_v06_nk_test.zip](https://github.com/julesontheroad/NSC_BUILDER/files/2563693/NSCB_v06_nk_test.zip)

**Comment by julesontheroad** [comment]
[NSCB_v06b_nk_test.zip](https://github.com/julesontheroad/NSC_BUILDER/files/2563852/NSCB_v06b_nk_test.zip)

**Comment by doctahoo** [comment]
Hi, I'm satelman (from the ElOtroLado forum).

This issue still happens to me, after using the v 0.6b test above. Isn't any other way to disable the counter?

Which code lines should be commented out?

**Comment by julesontheroad** [comment]
Yeah i see the issue I use other find /C in xci.bat. I'll try to move that things into python.

**Comment by julesontheroad** [comment]
**I toom both finds of in v0.6.1 so this should be solved already.**

**Comment by doctahoo** [comment]
Yeah, it is solved now! Thank you!!

**Comment by julesontheroad** [comment]
Closing this up as I consider it solved.
