### ISSUE TITLE
Adding simple-to-read SDK version in game info data ?

### ISSUE THREAD

**Issue by LosBaguettor** [julesontheroad/NSC_BUILDER#30]
Hello !  

thanks for this awesome tools but i do have a question/suggestion.  

Are you planning to Add simple-to-read "SDK version" in your "Game-info and FW requirements" section like XCI Explorer does ?  

I saw that we can get it from the Nut-info but that's a raw value (100925440 instead of 6.4.0.0 for example) so that's not really easy to read.  

I know that we can easily update with Choidujour but since SDK version is very important to know if a game will run or not on the firmware you are currently using, it would actually be awesome to be able to see this value before reencrypting without using an other tool.

**Comment by julesontheroad** [comment]
Will take a look.

**Comment by julesontheroad** [comment]
Implemented on master's python code, will add to next release. Now nut info will give a understandable sdk version number and for the info functions and extended databases:
- Games\Updates get meta sdk version and program sdk version
- DLCs get Meta SDK version and PublicData SDK version.
The updated databases are extended and extended keyless.
![xci](https://user-images.githubusercontent.com/42461174/57658661-02b43780-75e0-11e9-80ae-3b9cce648fd9.PNG)

**Comment by LosBaguettor** [comment]
Awesome work !  

Big thanks to you for adding this !
