### ISSUE TITLE
Rename old converted files to new format 

### ISSUE THREAD

**Issue by DavidRC1977** [julesontheroad/NSC_BUILDER#35]
Hi, congratulations for this great program. 
Until now, I have created a lot of xci files with your program including game base with update/dlc. In the older nsc builder version I used, the file format was "title name+multi+xcib" (no title Id and not update version). 
I would like to know if there's any option (I can't find it) for only renaming this files automatically to the new format "title name +title id+version+number of updates...".
If there is not available, it will be great if you can add it! 
Thanks a lot!

**Comment by julesontheroad** [comment]
Yes, there is a file renamer in the last version and it gives more options than the one used automatically in the new multis. 
You need to enter individual mode, add the files or folders, set to process the files and then it'll ask for:
1. Repack as nsp
2. Repack as xci
3. Repack as both
4. Erase Deltas from updates (without removing ticket)
5. Rename files

Use option 5 and follow the instructions it'll ask some questions to rename the files.

**Comment by DavidRC1977** [comment]
That’s just what I was looking for!!!! Best app ever !!!

Only in two games with two updates added in each one, at the time of renaming, it retrieves the old update number, not the newest one.

**Comment by julesontheroad** [comment]
Seems weird really. The way it works it'll show the version of the predominant game when there is several of them, so that should only happen if there are several updates inside the file and some is orphaned or from other game that is inside the same file.
