### ISSUE TITLE
[19868] Failed to execute script squirrel

### ISSUE THREAD

**Issue by healla** [julesontheroad/NSC_BUILDER#37]
Getting this error with some files.

- Calculating base-ids for:
        x:\game\gamename.xci
        x:\game\gamenameupdate.nsp

- Generating lists:
Traceback (most recent call last):
  File "squirrel.py", line 5293, in <module>
IndexError: list index out of range
[19868] Failed to execute script squirrel
File Not Found
---------------------------------------------------
*********** ALL FILES WERE PROCESSED! *************
---------------------------------------------------

**Comment by julesontheroad** [comment]
Try with the new version if you don't mind. I couldn't really reproduce that error.
