### ISSUE TITLE
Issue with Game info

### ISSUE THREAD

**Issue by Guilouz** [julesontheroad/NSC_BUILDER#4]
Is it normal I have no game info for other languages except for English after rebuild an XCI with his update ?

Original XCI : 
<img width="410" alt="capture d ecran 2018-11-15 a 20 57 49" src="https://user-images.githubusercontent.com/12702322/48578219-5be52c00-e919-11e8-8bc9-5b7000c6730e.png">

Repacked XCI with update 1.1.0 : 
<img width="410" alt="capture d ecran 2018-11-15 a 20 58 18" src="https://user-images.githubusercontent.com/12702322/48578243-6bfd0b80-e919-11e8-933c-0cbbefd7ece5.png">

**Comment by julesontheroad** [comment]
That's probably related to how xci explorer reads the files. The file in this case will have 2 control nca files and 2 meta nca files (one of each for update and base game), i'm actually surprised xci explorer shows the file as game revision 1.1.
Don't worry the switch will be able to identify game and update just fine.
