### ISSUE TITLE
Some bugs and strange things that I have discovered

### ISSUE THREAD

**Issue by jlozes** [julesontheroad/NSC_BUILDER#5]
Helo,

When I translated the script I see some "endlocal" commands that seems unusful for me.

There is one at the bigeening of the "nsp.bat" script and an other in the "xci.bat" script (bigeening also).

In the main script, I've seen some of them at lines 326, 389, 649 (maybe the lines are a little differents because the translation change the number of lines of the file) but you have one just after the ":manual" label, just after the ":manual_INIT" label and the ":multi_manual_INIT" label.

An other thing, the "keys.txt" file must be defined without the "ztools" path and the file must be placed on the root of the script because it cause problem with "nut_RTR.py" that doesn't see the keys file because the script ("NSCB.bat") execute the command from his root path.

Thanks and great work, your script is very usful.

**Comment by julesontheroad** [comment]
Ah yeah I didn't I forgot to edit nut for the keys. Either way that it's set actually to help with profiles more than anything.

The endlocals are needed, those are used to counter delayedexpansion effects with files with weird characters.
For translations I plan to add them via cmd files like I do with the options when the program is more nearer to a finish state.

**Comment by jlozes** [comment]
Thanks for the answers.

For the "endlocal" I don't realy understand how you use them but I found a solution to include them in my script and they don't brake it anymore. If they are required I must include them.

For the translation I know it's difficult to add them in a batch script because of characters encoding but I can confirm that the script work with a "chcp 65001", it's easier to include this encoding table to translate the script in language like french or spanish witch have some accents letters.

I think I could close this issue but I have found an other problem that I will submit very soon in an other issue because it's totaly different.

**Comment by julesontheroad** [comment]
To close delayed expansion is only needed when you deal with special characters like **!**
What I do is open delayed expansion only  when needed and close it after. To close delayedexpansion you do it with an endlocal.
If you leave it open you won't come with isues unless you have special characers in the files.
