### ISSUE TITLE
Error in 0.86d with multi-pack

### ISSUE THREAD

**Issue by RichyH72** [julesontheroad/NSC_BUILDER#54]
Hi Jules,

I just tries 0.86d and it gave the following error in mult-pack

-------------------------------------------------
INDIVIDUAL PROCESSING ACTIVATED
-------------------------------------------------
-------------------------------------------------
                FILES TO PROCESS
-------------------------------------------------
The system cannot find the file DBL.txt.
The system cannot find the file DBL.txt.
.................................................
YOU'VE ADDED  FILES TO PROCESS
.................................................
WHAT DO YOU WANT TO DO?
......................................................................
"DRAG ANOTHER FILE OR FOLDER AND PRESS ENTER TO ADD ITEMS TO THE LIST"

Input "1" to start processing
Input "e" to exit
Input "i" to see list of files to process
Input "r" to remove some files (counting from bottom)
Input "z" to remove the whole list
......................................................................
*************************************************
Or Input "0" to return to the MODE SELECTION MENU
*************************************************

Drag file/folder or set option:

After this I get a new menu with options 

Drag file/folder or set option: 1
*******************************************************
CHOOSE WHAT TO DO AFTER PROCESSING THE SELECTED FILES
*******************************************************
Input "1" TO GENERATE NUTDB DATABASE
Input "2" TO GENERATE EXTENDED DATABASE
Input "3" TO GENERATE KEYLESS DATABASE (EXTENDED)
Input "4" TO GENERATE SIMPLE DATABASE
Input "5" TO GENERATE ALL 4 ABOVE DATABASES
Input "Z" TO MAKE ZIP FILES

******************************************
Or Input "0" to return to the list options
******************************************

Enter your choice:

Will there be an option to create nothing?

If you need more info please let me know.

Kind regards,

Richard

**Comment by julesontheroad** [comment]
Yeah, NSCB.bat got messed up during the merges. I'm correcting it right now, it works fine with the one on my pc but it seems that when i merged the master with the beta the beta not having some files made something go wrong or whatever. Well i'm on it, just need to check the rest of the files are fine.

**Comment by RichyH72** [comment]
Okay, thouhg it was me for a sec.
Will await the fixed version and gave that one a try.

**Comment by julesontheroad** [comment]
Should be fixed now https://github.com/julesontheroad/NSC_BUILDER/releases/tag/v0.86e
