### ISSUE TITLE
XCI to NSP not working if a space is in a path foldername

### ISSUE THREAD

**Issue by 20Phoenix** [julesontheroad/NSC_BUILDER#6]
XCI to NSP not working if a space is in a path foldername

**Comment by julesontheroad** [comment]
Do you mean in the imput? All my input folders have spaces and I didn't encounter that issue. Can you give me more details?

**Comment by 20Phoenix** [comment]
Sure. This is the path where NSCB.bat is:
"H:\SWITCH\tools\NSP to XCI\NSCB_v061_nk"
I have to rename it to:
"H:\SWITCH\tools\NSP_to_XCI\NSCB_v061_nk"

**Comment by julesontheroad** [comment]
Aha I see the issue, it's not with the program route but instead with the temporal folder when the work folder when it gets pass to either of the secondary batch. I'll look into it after I finish next release.

**Comment by 20Phoenix** [comment]
Please, one more help needed:
How can I split a build game including updates and DLCs back into its parts (base + update + DLCs) ?

**Comment by julesontheroad** [comment]
That one is planned. I'll start with it at the weekend. My plan is to do it by reading the meta nca so I can also rebuild them with new updates.

**Comment by julesontheroad** [comment]
Yes, it extracts and patch the needed files to secure and the packs it all as "nsp", "xci" or "both", depending on your config file.

**Comment by jlozes** [comment]
Helo,

To fix these problems, you have to use the "usebackq" in the "for /f" loops with file name that can contain spaces in the path.

In the v0.6.5 version, you should replace the following lines.
NSCB.bat file:
Line 887 (not tested):
`for /f "tokens=*" %%f in ( %~dp0logo.txt ) do (`

Replaced by:
`for /f "usebackq tokens=*" %%f in ("%~dp0logo.txt") do (`

Line 996:
`for /f "tokens=1* delims=[" %%a in (%w_folder%\fname.txt) do (`

Replaced by:
`for /f "usebackq tokens=1* delims=[" %%a in ("%w_folder%\fname.txt") do (`

Line 1000:
`for /f "tokens=1* delims=(" %%a in (%w_folder%\fname.txt) do (`

Replaced by:
`for /f "usebackq tokens=1* delims=(" %%a in ("%w_folder%\fname.txt") do (`

ztools\NSP.bat file:

Line 17:
`for /f %%x in (%w_folder%\nsp_fileslist.txt) do set row="%w_folder%\secure\%%x" !row!`

Replaced by:
`for /f "usebackq" %%x in ("%w_folder%\nsp_fileslist.txt") do set row="%w_folder%\secure\%%x" !row!`

Line 33:
`for /f %%x in (%w_folder%\nsp_fileslist.txt) do set row="%w_folder%\secure\%%x" !row!`

Replaced by:
`for /f "usebackq" %%x in ("%w_folder%\nsp_fileslist.txt") do set row="%w_folder%\secure\%%x" !row!`

ztools\XCI.bat file:

Line 22:
`for /f "tokens=*" %%f in (%w_folder%\nca_list.txt) do (`

Replaced by:
`for /f "usebackq tokens=*" %%f in ("%w_folder%\nca_list.txt") do (`

**Comment by julesontheroad** [comment]
Ah I didn’t know about useback, that’s precisely why I didn’t add quotes there. 
Yep, your solution should work.

**Comment by julesontheroad** [comment]
jlozes your solution seems to work fine. I uploaded as **63d5748a0536243468ef372616cc8c41d270cdd8**

**Comment by julesontheroad** [comment]
Completely solved in current master of the program
