### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by fycn** [julesontheroad/NSC_BUILDER#63]
Option 2: Multi-Pack mode 

Note: remember to press enter after each **dile**/folder dragged

Sorry to point it out, great work on this program!

Thank you

![image](https://user-images.githubusercontent.com/53659735/62414922-fee8ed80-b5ef-11e9-9053-4b2ab8d8a96c.png)

**Comment by julesontheroad** [comment]
Noted, will be fixed next release.
BTW i think you're using windows 7. In windows 7 and vista i think the console doesn't auto-resize but you can increase it's with in properties (clicking the left corner of the windows over the "C:\" logo)
I use 100 width and 38 height in the window size option.

**Comment by fycn** [comment]
thanks for the tip, fits the window much better

**Comment by julesontheroad** [comment]
Fixed

**Comment by fycn** [comment]
Hello, 

typo is there in v90 and v90b

Thanks!

![image](https://user-images.githubusercontent.com/53659735/64496667-a6071780-d275-11e9-8aad-6cc400d13b1e.png)
