### ISSUE TITLE
Can't split Zelda BOTW for fat32 format

### ISSUE THREAD

**Issue by steph9009** [julesontheroad/NSC_BUILDER#69]
Can't copy NSC-Builder output of Zelda BOTW for fat32 format, Windows alert saying "file is too big for destination" if trying.

File that can't be copied to microSD is number 02, instead 00-01-03 are fine.

**Comment by julesontheroad** [comment]
ok, i'll try with Zelda and check if the split size is wrong at some point. That happens with 0.9, right?

**Comment by steph9009** [comment]
Exactly, latest release of NSC_B used

**Comment by steph9009** [comment]
oh, I forgot to tell: i'm using x64 on Windows 10 x64

**Comment by julesontheroad** [comment]
So I checked yesterday and detected the error, it will be fixed in 0.91, which is due to some point this week.

**Comment by steph9009** [comment]
Hylia bless you.

**Comment by julesontheroad** [comment]
Should be working fine now. Leaving it open for comfirmation.
