### ISSUE TITLE
Bug with some files name

### ISSUE THREAD

**Issue by jlozes** [julesontheroad/NSC_BUILDER#7]
Helo,

I have found a bug when the end of the filename is a "2" (maybe a "1" also but my solution work for all files). For example, if I try to convert a file that is named "foo 2.xci", the output folder will be the message state of the echo command, it's because the "2" at the end of the filename without the extention will redirect the error output and will give an empty "fname.txt" file and this cause problem for the others steps of the script.

My solution is to replace the line 992:
`echo %filename%>"%w_folder%\fname.txt"`

By this one:
`echo %filename% >"%w_folder%\fname.txt"`

After that, you can add this line after the line 1003:
`set end_folder=%end_folder:~0,-1%`

Normaly, this will fix the issue.

**Comment by julesontheroad** [comment]
I'll look at it.

**Comment by julesontheroad** [comment]
Aha I see. If you put a file like that it affects the final folder's name didn't occur to me since all my files have proper names.
Either way I added your fix in commit **5b59f067d0812bc10a2d544e4c35bd7469111d87** thanks for letting me know. ;)

**Comment by jlozes** [comment]
To be honest I had tested a lot of solutions before finding this, I haven't think of the "2>" but after finding it it was logic but not so easy to find in a file that contain more than 1000 lines of codes that are not coded by myself.
I close this issue.
