### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by fycn** [julesontheroad/NSC_BUILDER#72]
NSB_90dx64

Option 2: Multi-Pack mode

Note: remember to press enter after each dile/folder dragged

Thank you

![Capture1](https://user-images.githubusercontent.com/53659735/65650140-8db62d00-dfd7-11e9-8ae5-13b5f870a4ae.PNG)

**Comment by julesontheroad** [comment]
Thanks it will be fixed in the new version that will be released tomorrow.

**Comment by julesontheroad** [comment]
Fixed now, thaks again
