### ISSUE TITLE
Compression NSZ "default level" squirrel error.

### ISSUE THREAD

**Issue by KurBonhart** [julesontheroad/NSC_BUILDER#75]
Hi,  NSC_BUILDER v0.92 x64 when select the default compression level with "d" squirrel error comes out, and if i put 17 manually in the command it compresses it to level 7. 

Thanks for this awesome tool.

![Captura](https://user-images.githubusercontent.com/56373357/66530900-09e95e00-eb0a-11e9-89a4-e5b738fa5e2e.PNG)

**Comment by jasii** [comment]
Same issue here

**Comment by julesontheroad** [comment]
Is fixed now:
https://github.com/julesontheroad/NSC_BUILDER/releases/tag/v0.92b
