### ISSUE TITLE
Possible to convert from retail to dev?

### ISSUE THREAD

**Issue by jonathan7183** [julesontheroad/NSC_BUILDER#76]
Hi, was just wondering is it possible that you can add a feature to drop in dev.keys and decrypt from retail nsps and convert to dev encrypted nsps?

**Comment by julesontheroad** [comment]
Would need to resign acid, create a new public\private pair for sig2 and resign sig1 though if i'm not mistaken, in case you want to use them without patches

**Comment by jonathan7183** [comment]
I think that would be fine without resigning acid and signature1 and creating a public/private for signature2... Is it possible that you can implement this sort of feature? Using the retail keys to unpack a retail encrypted nsp then use the dev keys to repack that nsp?
