### ISSUE TITLE
Problem converting+integrating update

### ISSUE THREAD

**Issue by matofesi** [julesontheroad/NSC_BUILDER#77]
I've just found the first game that wouldn't work after converting XCI+update to XCI - newly released Witcher 3. If I convert the XCI only the result works just fine, but after I add an update to it the resulting XCI (which is over 33MiB) wont work - trying to "insert" it on newest SX-OS gives the system error "cart or your console is damaged".
I use automatic mode for all conversions and everything I tried until now worked fine, but this seems to be the first game that results in file being over 32GB. Is there something I'm doing wrong or is it some kind of limitation that can/can't be worked around? Or maybe I'm just missing some option I need to set...?

**Comment by julesontheroad** [comment]
I can't do anything. Cards bigger than 32GB won't work TX would need a 64GB to make them work and I'm not sure the system supports them currently.
