### ISSUE TITLE
Typo in sq_tools.py (keys check)

### ISSUE THREAD

**Issue by lahma69** [julesontheroad/NSC_BUILDER#78]
Line 463 in [sq_tools.py](https://github.com/julesontheroad/NSC_BUILDER/blob/master/py/ztools/lib/sq_tools.py):

```
if 'master_key_09' not in checkkeys:
    print("master_key_08 is Missing")
```
When **master_key_09** cannot be found, it says that **master_key_08** is missing.

**Comment by julesontheroad** [comment]
Thanks, i'll check and probably update the latest release silently when i have time to rebuild the files into exe again.

**Comment by julesontheroad** [comment]
Closing sine it was fixed on last release.
