### ISSUE TITLE
nscb batch set /p -> choice

### ISSUE THREAD

**Issue by crwusiz** [julesontheroad/NSC_BUILDER#87]
![2019-11-09_111551](https://user-images.githubusercontent.com/43285072/68521248-8f675600-02e2-11ea-889a-5dcc1abc76d6.jpg)

choice /c 1234567890l /m "Choice Menu"
if %errorlevel%==1 goto normalmode
if %errorlevel%==2 goto multimode
if %errorlevel%==3 goto SPLMODE
if %errorlevel%==4 goto INFMODE
if %errorlevel%==5 goto DBMODE
if %errorlevel%==6 goto ADVmode
if %errorlevel%==7 goto JOINmode
if %errorlevel%==8 goto ZSTDmode
if %errorlevel%==9 goto RSTmode
if %errorlevel%==10 goto OPT_CONFIG
if %errorlevel%==11 goto LegacyMode

**Comment by crwusiz** [comment]
cmd size fix
->
MODE CON lines=40 cols=90

**Comment by julesontheroad** [comment]
Ok got it, so impose size for the batchfile and use choice for the initial menu.
The thing with choice is that I was planning to add more options, at least a 10th one that wasn't added yet and choice need single characters. 
I may think about regrouping the options though. In general is possible that the batch needs some reorganizing.
