### ISSUE TITLE
Rename - add Region

### ISSUE THREAD

**Issue by pmferraro** [julesontheroad/NSC_BUILDER#88]
Hi is possible to add region to rename function? For example:
The Witcher 3 Wild Hunt — Complete Edition (**US**) [0100BFE00E9CA800] [v196608]

**Comment by julesontheroad** [comment]
Yeah I planb to add more stuff to the renamer but I'm a little behind on planned features currently.

**Comment by pmferraro** [comment]
THANKS A LOT. GOOD JOB
