### ISSUE TITLE
NSZ Source ERROR

### ISSUE THREAD

**Issue by pmferraro** [julesontheroad/NSC_BUILDER#89]
When i use NSZ to make multi-PACK XCI i have error  OBJECT HAS NO ATTRIBUTE
![image](https://user-images.githubusercontent.com/47057909/68984358-610bde00-07ee-11ea-9a04-f88d9e92939d.png)

**Comment by julesontheroad** [comment]
Hmm first time i see the error, hard to know what's the issue without looking at the file.

**Comment by julesontheroad** [comment]
Closing it for now as I didn't get more reports of it happening
