### ISSUE TITLE
Multi-content Base ID scan doesnt work with nsz files

### ISSUE THREAD

**Issue by deadair3210** [julesontheroad/NSC_BUILDER#99]
Not sure if this is a known issue, but when trying to scan nsz files for the base ids to deal with possible merging, the program will fail with **Exception: '_io.TextIOWrapper' object has no attribute 'cnmt_get_baseids'**

**Comment by deadair3210** [comment]
Still happens with latest build, nsz files all error out and are not scanned for their adds and added to the correct lists

**Comment by julesontheroad** [comment]
Ok i got what you were saying, i didn't understood you apparently. Is the argument "split_list_by_id", that argument only accepted xci or nsp files and i didn't add an exception for other types apparently.
Well i extended the list to nsp and xci. I only used nsz\xcz for single jobs so i didn't realized that.
I just made a commit to beta.

**Comment by deadair3210** [comment]
Will check when I get home later tonight from work. The issue im having is nsz files don't work with the seperate for base IDs option for multicontent packs

**Comment by deadair3210** [comment]
Fix works great! Detects nsz base ids perfectly fine now!

**Comment by julesontheroad** [comment]
Ah I see you're using python then. I still need to work some issues with the Google Drive Library I added and the exe builds but if you use python and want to try it there's instructions of how it works on the changelog.

**Comment by deadair3210** [comment]
Can't use Drive API, my college has it turned off or I would test it

**Comment by julesontheroad** [comment]
If you're curious it also works with direct public links if they aren't over quota. I have something to copy them to a private drive directly for those cases but I didn't add it yet.
For the private drives it will work too with added folders or files from other owner.

**Comment by deadair3210** [comment]
Oh cool, might mess around with it when I get a chance
